### ISSUE TITLE
Add an optional prop for a dismiss / close button on the Alert component

### ISSUE THREAD

**Issue by 1Copenut** [CMSgov/design-system#102]
## Description

Alerts serve many purposes, mostly to inform users of time-sensitive or in-passing information. Sometimes this information needs to persist, other times it is simply a confirmation, and users should be able to dismiss it.

## Additional information [optional]

Per the 18F WDS recommendation on alerts, I propose we add an optional prop to the Alert.jsx component for a dismiss UI mechanism. A button seems a good candidate.

**Comment by benkutil** [comment]
@1Copenut thanks for the suggestion. We'll capture this as an internal improvement for the Alert component, but don't intend to implement at this time.
