### ISSUE TITLE
Autocomplete clear button alignment

### ISSUE THREAD

**Issue by brianseek** [CMSgov/design-system#1060]
The autocomplete clear button uses a transparent variant small size button component and inherits the normal button padding. This causes the text to look misaligned with the field. 

I would suggest to 0 out the right-padding or allow us a prop on autocomplete to pass a className to the clear button.

**To Reproduce**
1. View the Autocomplete component with a clear button

**Expected behavior**
Have the clear text be right aligned with the field input.

**Comment by pwolfert** [comment]
This was filed in Jira at a later date by the original poster. Closing this issue because progress can be tracked there. As an update, this was approved for work today by our stakeholders.
