### ISSUE TITLE
Stylelint 14 rule updates

### ISSUE THREAD

**Issue by sophaskins** [CMSgov/design-system#1237]
Stylelint v14 [removed](https://stylelint.io/CHANGELOG#1370) deprecated rules (`*-blacklist`, `*-requirelist` and `*-whitelist`), replacing them with `*-disallowed-list`, `*-required-list` and `*-allowed-list`. 

The `sylelint-config-design-system` includes rules that have been deprecated, making it incompatible with newer versions of Stylelint.
https://github.com/CMSgov/design-system/blob/7463c1672b80848cb747cc82440d5b420060d249/packages/stylelint-config-design-system/index.js#L47-L55

It would be rad to get that list updated, so that we can use newer versions of Stylelint.
Thanks!

**Comment by sophaskins** [comment]
(I'm happy to put together a PR to this effect, if that is helpful!)

**Comment by pwolfert** [comment]
Thanks for the issue, @sophaskins! We're actually planning to get rid of the `stylelint-config-design-system` package entirely. @forrestbaer, do you know if we're ready to actually remove them from our repo? I don't see any references to them anymore.

**Comment by forrestbaer** [comment]
Oh wow I never saw this tagging, @sophaskins any DS releases after 3.2.2 will have the new stylelint changes defined in \`.stylelintrc.js\` in the core DS repo and are no longer being defined per package. Closing this as it has been resolved with latest DS versions.
