### ISSUE TITLE
Does this replace the Assets Framework?

### ISSUE THREAD

**Issue by thecristen** [CMSgov/design-system#135]
The Assets Framework referring to: https://assets.cms.gov/resources/framework/3.4.1/Pages/#
Phrased another way, is Assets sunsetted?

**Comment by raj923** [comment]
The Assets framework will be maintained for another couple of years since it’s used on several CMS websites/applications. All new developments will be using Design system framework moving forward.

**Comment by benkutil** [comment]
@thecristen, at this time, no, it does not replace Assets. We plan to maintain [Assets](https://assets.cms.gov/resources/framework/3.4.1/Pages/) for another couple of years, as its used by several CMS applications/Websites. All new development will use Design System.

Thanks for the question, hope that helps.
