### ISSUE TITLE
StepList content overlaps an open HelpDrawer

### ISSUE THREAD

**Issue by scitech** [CMSgov/design-system#1407]
**Describe the bug**
At tablet-ish viewports, when the help drawer is open, the content of a StepList will overlap the help drawer.

**To Reproduce**
1. Go to https://www.healthcare.gov/tax-tool/#/premium-tax-credit
2. Click "Find my Form 1095-A" to open help drawer
3. Resize browser to like 800px wide
4. See problem

**Expected behavior**
Help drawer should be on top of all page content.

**Screenshots**
![image](https://user-images.githubusercontent.com/4130722/146616048-bd51e7e3-c9f0-48d3-9386-11092c661940.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Chrome
 - Version: 96

**Comment by pwolfert** [comment]
@scitech, do you know if this is still an issue in your app?

**Comment by scitech** [comment]
@pwolfert this is fixed 🎉
