### ISSUE TITLE
I would like to replicate your KSS setup

### ISSUE THREAD

**Issue by NathanVG** [CMSgov/design-system#147]
Hi, 

not really an issue, more a question. I read the article on Medium about this design system and was very impressed and as such I would like to replicate it so I can use it myself.

Is the purpose of this repo sharing the design system itself or the functionality of how it was made? I get the impression it's more the former than the latter, and as such I was wondering if it would be possible of maybe creating a guide on how you did the setup?

kind regards, 

Nathan

**Comment by sawyerh** [comment]
Hi @NathanVG, the repo's purpose is for folks using or contributing to the design system. The repo is open source and you can view more of the [licensing info here](https://github.com/CMSgov/design-system/blob/master/LICENSE.md), so feel free to fork this repo if you'd like to use its tooling. 

Here's some more info that might help:

- [Contributing info](https://github.com/CMSgov/design-system/blob/master/CONTRIBUTING.md)
- [How documentation is written and generated](https://github.com/CMSgov/design-system/wiki/writing-documentation).
