### ISSUE TITLE
Proposal: Add "Exposed Within" pattern (and "Inset" component)

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#178]
Following the [pattern proposal guidelines](https://github.com/CMSgov/design-system/wiki/Pattern-lifecycle#proposing-new-patterns), I'd like to suggest that we add the "Exposed Within" form pattern to the design system. Also included in this pattern is a new component, which for lack of a better name, I'm calling "Inset". Both of these are detailed below.

## Proposal Part 1: Exposed Within 

The "Exposed Within" pattern is a way to progressively reveal an additional question only when it is relevant to the user. This takes the form of a question that is visually nested below a checked radio/checkbox field. 

| Example |
| --- |
| ![exposed-within](https://user-images.githubusercontent.com/371943/32066358-7b54b570-ba4d-11e7-8dd2-422535547bfe.gif) |

### What user need this pattern solves

There may be times when a service needs to ask the user for more information based on how they answered a previous question. This pattern allows the form to be as minimal as possible, and only surfaces questions that are relevant to the user's circumstances.

### Supporting evidence

1. Some research on this pattern was mentioned in [Web Form Design](http://rosenfeldmedia.com/books/web-form-design/), by Luke Wroblewski. In their research they asked users to use 9 different form patterns and used eye tracking software to measure the number and duration of their fixations. The average number of eye fixations indicates the level of effort required to parse a form. And the length of fixation indicates the time spent looking at each element.

    > The “expose within radio buttons” method also hid irrelevant form inputs from people until they needed them. This meant it was easy on the eyes and completed quite quickly. In fact, this was the fastest solution we tested and had the lowest number of average fixations.

2. This is pattern is [recommended by GOV.uk](http://govuk-elements.herokuapp.com/form-elements/#form-toggle-content) 
3. and [recommended in the Co-op Design Manual](http://coop-design-manual.herokuapp.com/styles/forms/form-patterns.html#progressive-reveals)

### Alternative patterns

This pattern doesn't solve for all use cases, but is a good solution for situations when you need to progressively reveal _one_ piece of information. If you need to ask for more than one thing, an alternative pattern may be better, like revealing the information below the original question's fieldset or on a separate screen.

----

##  Proposal Part 2: Inset component

While prototyping the Exposed Within pattern above, I ran into the need for a new component that visually looks like the content is nested, while having a border that leads the user's eye to the element that it is nested within. 

### What user need this pattern solves

The Inset component is meant to draw attention to important content, or to associate a block of content with another element. It can be used as part of the Exposed Within pattern, in a progressive disclosure accordion (ie. for help text), or on its own as a way to distinguish a block of text from its surrounding content.

| Example |   |
| -------- | --- |
| Progressively disclosed text | ![inset-disclosure](https://user-images.githubusercontent.com/371943/32067487-6af13c68-ba51-11e7-92ca-e12ebec88ffa.gif)|
| Important content | ![image](https://user-images.githubusercontent.com/371943/32067653-f7b7b0a0-ba51-11e7-9ce6-8fc9cadd5c1c.png) |

### Alternative components

This component is somewhat similar to the `Alert` component, in that it can be used to draw attention to important content. However, the Inset component is also used to visually associate its content with neighboring elements, and can be used to indicate a nested relationship.

The `Alert` component also has a similar left border, but that visual styling could change, as it has in the past.

### Supporting evidence

1. This is a pattern [recommended by GOV.uk](http://govuk-elements.herokuapp.com/typography/#typography-inset-text). In their CSS, they named it `panel`, however I find that confusing and not very accurate.

**Comment by mliupaeter** [comment]
+1

**Comment by sawyerh** [comment]
A prototype of this pattern is available here: https://github.cms.gov/CMS-WDS/ds-healthcare-gov/pull/4
