### ISSUE TITLE
SVGIcon should render 'data-testid' (and all data- attributes)

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#1880]
**Describe the bug**
SVGs should render `data-` attributes, [according to spec](https://svgwg.org/svg2-draft/struct.html#DataAttributes) ([see also](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*)). `SVGIcon` (and therefore all other DS `Icon`s), will not render these attributes. 

There are bugs in Testing Library such that `getByRole` queries on images that are `aria-hidden` will not work with the `name` option (accessible name, referencing the SVG's `title` content), so using a `data-testid` attribute is the best fallback (the only one that works without resorting to plain CSS queries). [Reference bug report](https://github.com/testing-library/dom-testing-library/issues/1132)

**To Reproduce**
1.  Import any `Icon` or use the `SVGIcon` component with any valid SVG content
2. Pass in a `data-testid` prop. This is not flagged by TS, because it's valid
3. View the rendered SVG, which will have no `data-testid` attribute
4. Try with any basic HTML Element in JSX, such as a `div`
5. `data-testid` is rendered (as is any `data-` attribute)

**Expected behavior**
`data-` attributes are rendered

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [OSX 12.4]
 - Browser [Chrome]
 - Version [latest]

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by Josh68** [comment]
> 👋🏻 Hi Josh, thanks for reporting this. I've got it [logged in Jira ](https://jira.cms.gov/browse/WNMGDS-1712). I'll talk to the team and get this prioritized.

Thanks, @scheul93!

**Comment by forrestbaer** [comment]
Fix has been fully released in `5.5.0`
