### ISSUE TITLE
Advanced table behaviors: Sorting, Paging

### ISSUE THREAD

**Issue by asarazor** [CMSgov/design-system#195]
## Description

We have some advanced table features in our backlog. Does the core team have either of the following in your roadmap for table or list features?

1. Paging (classic style)
2. Sorting (by column header)

**Comment by sawyerh** [comment]
Hey @asarazor 👋 We have tickets in our backlog related to creating React components for Lists and Tables, however haven't yet discussed if those components include advanced functionality like paging or sorting. I could see both of those features being useful especially in the Table component. 

I'll make a note of this, and also happy to discuss these ideas further here.

**Comment by asarazor** [comment]
Hi @sawyerh, here are some mock-ups of how I was thinking of implementing the sorting and filtering. Both are visually pretty straight forward.

# Sorting 

Columns can be made `sortable`. Which will express the visual and functional behavior you see below. In case it's not clear, the whole table will be sorted.
![ui components table sorting](https://user-images.githubusercontent.com/19854/33581581-600506da-d91f-11e7-9ff8-df8830833a4a.png)



I'm not that sold on the arrow icons used in the sorting, but think it's the clearest that fontawesome provides for this use-case, so I'm living with it.

N.B. If sorting and paging are combined, then sorting will sort by the entire dataset available, not just what is visually displayed.

# Paging

Paging is quite standard. I'm proposing we don't use First / Last links, to limit the clutter in the component.
![ui components table pagination](https://user-images.githubusercontent.com/19854/33580165-1ee38172-d91a-11e7-88e1-69f91875e51b.png)

--

These two features may get pulled into a sprint over the coming month, for now feel free to offer your suggestions.

**Comment by 1Copenut** [comment]
I like this approach a lot for sorting tables. Using a link inside the `<thead> <tr> <th>` provides good semantics; sorting a table often requires a database roundtrip, and a page reload. At the very least, a URL string might change or have parameters appended. Links and URL changes offer good UX to this feature.

If filtering by column(s) is on the future roadmap, you could consider a button to control a popup menu inside your `<th>` tags. I have previously tested markup that used a link for sorting, with the button next in the source order, and a hidden menu absolutely positioned. This worked well with keyboards and the VoiceOver screen reader. I believe it could work well with NVDA and JAWS also.

**Comment by sawyerh** [comment]
@asarazor thanks for sharing – I think this is looking good!

The VA Caseflow team had a similar need for an advanced table component (sortable and able to handle large'ish datasets). Their usecase was a little different — they needed expandable rows — but there might be some useful takeaways in some of the research and design work they've already done: https://github.com/department-of-veterans-affairs/caseflow/issues/3102

Here's a GIF of what the table looked like, and is more or less what it looks like in production right now. (Just sharing in case it's useful):

![documentstable](https://user-images.githubusercontent.com/371943/33615569-7b677456-d9a8-11e7-94e8-be22c615e82c.gif)

**Comment by benkutil** [comment]
Thanks @asarazor. I'm going to close this ticket for the time being. We've captured it on a list of possible future improvements, but don't intend to implement this currently.
