### ISSUE TITLE
Email address not valid - WPMG_Web@cms.hhs.gov

### ISSUE THREAD

**Issue by JimCollinsDC** [CMSgov/design-system#1952]
email sent to WPMG_Web@cms.hhs.gov  bounces as not a valid address.

**Comment by forrestbaer** [comment]
@Karak888 @pwolfert Should we remove this link and perhaps convert it to a link to https://design.cms.gov/contact? This particular email address is listed as an address for product owners of the CMSDS.

**Comment by pwolfert** [comment]
@forrestbaer, I like that idea 👍
