### ISSUE TITLE
Doc Site bug: Color hex values switch upon refreshing the page or selecting a theme

### ISSUE THREAD

**Issue by kevinfiol** [CMSgov/design-system#2090]
**Describe the bug**
Upon navigating to the `/foundation/color` page for the Healthcare or Medicare theme, I can see the correct hex values for the selected theme:

![image](https://user-images.githubusercontent.com/4752973/187535395-5e88e4a6-9fd1-4b39-ac7b-65d8e24c8187.png)

However, upon refreshing the page, the hex values switch to that of the Core theme:

![image](https://user-images.githubusercontent.com/4752973/187535491-1784e1e1-aaf3-48d8-b9f9-82beb51044a2.png)

The issue also happens if you switch the theme from Healthcare -> Core -> back to Healthcare.

**To Reproduce**
1. Go to https://design.cms.gov/
2. Select Healthcare or Medicare from the theme dropdown
3. Navigate to `Foundation > Color`
4. See correct hex values
5. Refresh page
6. Hex values are now incorrect

**Expected behavior**
Expect the values to remain the same on page refresh.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser Firefox/Brave
 - Version Latest

**Additional context**
N/A. This caused some confusion among our devs/design team, because if you simply try to link someone to https://design.cms.gov/foundation/color/?theme=healthcare , it will show the wrong hex values.

**Comment by kevinfiol** [comment]
Upon testing this again, it appears the problem only happens in Firefox. When using Brave or Chromium the page flashes for a bit, but will show the correct hex values.

On initial load in Firefox, the page fails to refresh to show the correct hex values.

**Comment by pwolfert** [comment]
Confirmed that it's not fixed.

**Comment by pwolfert** [comment]
I just realized that https://github.com/CMSgov/design-system/commit/383a7fdb391bbc2210f1101b98d497c4e0ff2e42 has not been deployed to our doc site yet

**Comment by pwolfert** [comment]
@kevinfiol, we deployed the fix to our doc site, but I'm afraid the issue still exists within Firefox. I've been able to reproduce the issue in a local dev build in Firefox, so I'll be working on fixing it.

**Comment by pwolfert** [comment]
@kevinfiol, I tested it in Firefox in production, and it's working for me. Let me know if you have any trouble with it.
