### ISSUE TITLE
Anchor button focus state text color reverts to baseline dark color, does not have sufficient contrast

### ISSUE THREAD

**Issue by erichuffman** [CMSgov/design-system#2110]
**Describe the bug**
Color of text on anchor buttons when in focus state (and not previously visited) does not retain the "hover" color value.

**To Reproduce**
1. In a new private browser window, go to: https://design.cms.gov/storybook/iframe.html?id=components-button--all-anchor-buttons&globals=theme:medicare&args=&viewMode=story
(note: use a private/incognito window so that `:visited` state does not apply to the links)
2. Use keyboard only navigation (tab / shift+tab).
3. Navigate to "Anchor button on-dark", and "Anchor button solid" examples
4. Note that button text changes to dark color when `<a>` element has focus (and the URL of the `href` has not been visited)

**Expected behavior**
The text `color` value should retain the same `--color-h` value that's applied when hovering over the element (or the element has focus _and_ is hovered over, or the link has been visited and has focus).

**Screenshots**
![image](https://user-images.githubusercontent.com/928118/188937645-42a2d25f-4247-446f-b625-4f95665bb859.png)

**Desktop:**
 - OS: iOS
 - Browsers: chrome, FF, safari
 - Version: latest builds

**Smartphone:**
_Not a major issue in touch environments unless keyboard/assistive devices are used._

**Additional context**
Anchor buttons are used quite frequently on the static (Drupal) Mgov site. We have an override in place for now to address this. It looks like the simplest solution would be to add the `color` property/value from [line 40](https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/styles/components/_Button.scss#L40) in the `_Button.scss` file to the ruleset on [line 22](https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/styles/components/_Button.scss#L22)? If this sounds good to you all I can submit a PR.

**Comment by pwolfert** [comment]
@erichuffman, thanks for reporting this and for your analysis! We're now tracking it in Jira with https://jira.cms.gov/browse/WNMGDS-1911. If you have time, we'd gladly accept a PR to fix this. I like your fix because it makes those rules more consistent! If you don't have time, you've basically solved it for us already 😄

**Comment by pwolfert** [comment]
@erichuffman, this fix will be included in our next patch release
