### ISSUE TITLE
Add variations of components that use Spanish

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#2244]
## What
It would be useful to include variations of components that are in Spanish. See an example here from the [USWDS](https://designsystem.digital.gov/components/pagination/) 
<img width="1085" alt="spanish and english versions" src="https://user-images.githubusercontent.com/10236001/201421743-8409f583-80ab-4f8f-9b05-7f73a6234aa4.png">

## Why
This would help catch issues such as spacing, text wrapping, etc. before teams are working with the components in their tool. To consider this also shows that we are being more inclusive in our designs since English isn't the only language being used.

**Comment by forrestbaer** [comment]
Hey @SparrowSpit, this is currently possible by messing with the settings in any storybook story, i.e. https://design.cms.gov/storybook/?path=/story/components-pagination--default&globals=language:es

Are you suggesting these examples include the multiple versions all in one story? This might be a little tricky as the language setting is set at a higher level than the component, so it would need to be done in multiple stories, which might not be great for experience on the docs site.

I wonder if this might be handled better via an addition to accessibility docs on the docs site to include a note about checking components in other languages and how to do so via the storybook controls?

**Comment by forrestbaer** [comment]
Hey @SparrowSpit just wanted to check on this one, will close next week if I don't hear back.

**Comment by SparrowSpit** [comment]
Sorry I hadn't responded before. I agree with your comment about " this might be handled better via  ..." Feel free to close this and we can work on documentation.
