### ISSUE TITLE
Improve documentation around disabled buttons

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#2255]
**Describe the bug**
Currently we have very[ limited, high level guidance](https://design.cms.gov/components/button/?theme=healthcare#usage) about using disabled buttons. I'd prefer to see something much more opinionated as is the stance for [the VA design system's guidance on disabled buttons](https://design.va.gov/components/button/#do-not-disable-buttons).

I'd suggest borrowing from our friends at the VA but rewriting. Feel free to edit but something like:

---

### Do not use disabled buttons
Disabling a “button” to act as a guide to the level of form completion is a common anti-pattern (i.e. you are not able to proceed to the next step until the form contains enough data).

#### Why it is a problem
1. Buttons tend to have call to action text that match what users want to do so people try to interact with them. 
2. They have terrible color contrast.
3. They don't provide feedback and tell you _why_ they are disabled. They communicate that something is off, but very often that is not enough information. As a result, users are left wondering what’s actually missing, and consequently are locked out entirely. 
4. Assistive technologies like [screen readers](https://www.nngroup.com/articles/touchscreen-screen-readers/) and [switches](https://en.wikipedia.org/wiki/Switch_access) are usually not even able to navigate to disabled buttons.

For these reasons, disabled buttons can be frustrating for all users but especially those with cognitive disabilities and those who use assistive technologies.

### Is it ever valid to disable a button?
Post-form submission or post-action it can be appropriate to disable the submit or action button as the system is in-between states and loading or taking action. This behavior is often seen on buttons that make a purchase or reservation to prevent the user from accidentally triggering the action multiple times.

If you must disable a button then we suggest doing it with aria-disabled vs. the HTML5 attribute of "disabled." An example could look like:
`<button disabled aria-disabled="true">Save your work</button>`

Note that VoiceOver's rotor will list all buttons despite their state. A button with disabled as well as the button with aria-disabled will be labeled as "dimmed button" which is useful information for a user.

---

**Comment by pwolfert** [comment]
I love this

**Comment by pwolfert** [comment]
Tracked under https://jira.cms.gov/browse/WNMGDS-2231

**Comment by forrestbaer** [comment]
Closing as resolved with #2437
