### ISSUE TITLE
SingleInputDateField calendar button submits forms when clicked

### ISSUE THREAD

**Issue by anthony-kopczyk** [CMSgov/design-system#2267]
**Describe the bug**

The calendar button/icon on the `SingleInputDateField` component with the modal dialog for picking dates has a button that's not set to `type='button'`. This is causing our form to submit when the user tries to select a date.

**To Reproduce**

- Create a form on an html document
- In the form, add a `SingleInputDateField` with the date picker.
- Click the date picker button
- See the form has been submitted

**Expected behavior**

The component should either use `type='button'` so that forms are not submitted, or should have an option to set the type of the button.

**Screenshots**

Not applicable

**Additional context**

None

**Comment by pwolfert** [comment]
This is definitely a bug. Thank you for reporting it, @anthony-kopczyk! We're going to implement a fix and publish a patch release today or tomorrow.

**Comment by Karak888** [comment]
Corresponding Jira Ticket #[https://jira.cms.gov/browse/WNMGDS-2101](url)
