### ISSUE TITLE
Issue with MGov upgrade and 3rd-party component with button set to aria-disabled="false"

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#2303]
I'm upgrading MCT to ds-medicare-gov v6.0.5 and am experiencing a new issue, caused by the following style declarations:

https://github.com/CMSgov/design-system/blob/e4015898223cc3f9796c4cc107d77037731a7def/packages/design-system/src/styles/components/_Button.scss#L61

https://github.com/CMSgov/design-system/blob/e4015898223cc3f9796c4cc107d77037731a7def/packages/design-system/src/styles/components/_Button.scss#L28

We (shouldn't be, but are, for the moment) using [react-collapsible](https://github.com/glennflanagan/react-collapsible) as the basis for collapsible sections on many of our pages. This component flips between `[aria-disabled="false"]` and `[aria-disabled="true]` on the collapsible's toggle , instead of just adding and removing `aria-disabled` altogether.

The referenced declarations treat the toggle with `[aria-disabled="false"]` as though it's disabled.

For declarations like this to not have unintended consequences, you many need to qualify, e.g.:

```css
.dc-c-button {
  [aria-disabled]:not([aria-disabled="false"]) {
    ...
  }
}
```

**Comment by Josh68** [comment]
I would think about issuing a ticket on react-collapsible, but [this reference](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled) clearly states that `aria-disabled` can be programmatically changed in two ways:

> Toggle the value to false (or remove the attribute entirely)

So I think qualifying this and similar declarations is probably the best solution.

**Comment by pwolfert** [comment]
We're working on this this sprint under https://jira.cms.gov/browse/WNMGDS-2153
