### ISSUE TITLE
[WNMGDS-2241] External link icon isn't communicated to screen readers

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#2340]
**Describe the bug**
The [external link icon](https://design.cms.gov/storybook/iframe.html?globals=theme:healthcare&id=patterns-third-party-external-link--third-party-external-link&viewMode=story) displays visually the intention of the icon to sighted users but there isn't a similar indication for non-sighted users.  

**To Reproduce**
1. Go to [external link icon](https://design.cms.gov/storybook/iframe.html?globals=theme:healthcare&id=patterns-third-party-external-link--third-party-external-link&viewMode=story) in Safari
2. With VoiceOver, navigate to the link/button and icon so that the link text is read out
3. No mention is made of the link to an external site except for the link text. This is clearer when you change the text of the button/link to something that doesn't reference the external site since most don't

**Expected behavior**
As a screen reader user I would expect to be able to be notified that I'm visiting an external site just as a user can see that this is going to happen.

**Additional notes**
I did some testing and it looks like this (simplified example) will solve our issue:
`<button type="button">U.S. Health Services
<svg role="img" class="ds-c-icon ds-c-icon--external-link ds-u-margin-left--05 aria-labelledby="desc"><title id="desc">This link goes to an external site</title>`

So, we want to add role=img and aria-labelledby to our svg and then add a title element. 

I tested this with VoiceOver, NVDA, and JAWS and all read out the button text and then "this link goes to an external site."

**Comment by Karak888** [comment]
Jira ticket Number for this: WNMGDS-2241

**Comment by forrestbaer** [comment]
Closing as resolved with #2431
