### ISSUE TITLE
Pagination component throwing an error on Safari 13.x 

### ISSUE THREAD

**Issue by nichia** [CMSgov/design-system#2379]
**Describe the bug**
When using older version of Safari (13.x and before) the Pagination component throws an error `media.addEventListener is not a function. (In 'media.addEventListener('change', listener)', 'media.addEventListener' is undefined)` which then crashes the application.

**To Reproduce**
1. Go to [Pagination component](https://design.cms.gov/storybook/?path=/story/components-pagination--default&globals=theme:healthcare) on Safari 13.1

**Expected behavior**
Expecting to see the Pagination information and not having this issue causing the application to crash.

**Screenshots**
![Screenshot 2023-02-10 at 2 01 08 PM](https://user-images.githubusercontent.com/20322880/218175669-b08c99ec-a6c8-4fbe-83f1-3ca691d51457.png)

**Additional context**
Safari 13 is [outside the scope of supported browsers](https://design.cms.gov/guidelines/browser-support/), but as our application currently still supports this version, could we consider adding a guardrail like try/catch to prevent the mediaMatch Event errors from crashing the application.  Also came across this write-up on [handling this issue on the older Safari versions](https://mosesoak.medium.com/responsive-layout-gotcha-watch-out-for-older-safari-versions-70275b0fae21) that might be helpful.

**Comment by pwolfert** [comment]
Fixed by https://github.com/CMSgov/design-system/pull/2398
