### ISSUE TITLE
[Accessibility] Add documentation for adding "Error" to page title

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#2432]
**Description**
Currently there is room to improve the error validation experience for those who use assistive tech. I recommend following the pattern that [UK. gov uses](https://design-system.service.gov.uk/patterns/validation/#how-to-tell-the-user-about-validation-errors) which prepends the word "Error" to the page title attribute. 

This will provide another avenue of feedback for screen reader users, allow them to better understand what's happening on the page, and therefore improve their chances of successfully completing the page. 

Documentation to be added is below. Possibly add to the Forms pattern page?

> add ‘Error: ’ to the beginning of the page <title> so screen readers read it out as soon as possible

**Comment by SparrowSpit** [comment]
Note: This may require a convo with stakeholders about a possible change/addition.

**Comment by Karak888** [comment]
Jira ticket added under to be verified: [https://jira.cms.gov/browse/WNMGDS-2254 ]
