### ISSUE TITLE
Add a print icon

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#2439]
## What
MCT has been using FontAwesome for several icons, and now we're stripping it out in favor of CMSDS icons. The only thing we're missing right now is a print icon, [like this](https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/print.svg). I am hacking it in using `SVGIcon` and a `path` copied over.

## Why
- Allows us to abandon 3rd-party icons, which have accounted for a sizeable amount of extra payload
- It does not exist in the DS as its own icon
- We use this icon all over MCT, and it appears HC.gov could also use one

**Comment by zarahzachz** [comment]
No new progress to report on this.

We were asked to do [discovery regarding icons](https://confluence.cms.gov/display/HCDSG/Icons+in+the+Design+System) and no work has been prioritized in implementing this. 

I believe there was still an outstanding question for the design system team regarding the legality of our design system providing a subset of FontAwesome's (our design system is open source and free for anyone to use, so can we legally provide FA icons, which are under a paid license? [Their license agreement says no.](https://fontawesome.com/license#what-creators-may-not-do)).

Keeping this issue open for the incoming team to run with.

**Comment by jack-ryan-nava-pbc** [comment]
Hi folks, I believe we now have print icons. Please see the documentation [here](https://design.cms.gov/components/icon/?theme=core) and let me know if you have any questions.

**Comment by Josh68** [comment]
@jack-ryan-nava-pbc, looks like it's there. We're just way behind on versions. Working on that. Seems like this can be closed, unless anyone else has comments. Also, I don't see the addition of this icon in release notes, but I could be missing it.

**Comment by jack-ryan-nava-pbc** [comment]
@Josh68 The icon was added in Version 11 of the Core Package: https://github.com/CMSgov/design-system/releases/tag/%40cmsgov%2Fdesign-system%4011.0.0
