### ISSUE TITLE
`inputRef` prop being passed into DOM when using <Dropdown />

### ISSUE THREAD

**Issue by austindh** [CMSgov/design-system#2493]
**Describe the bug**
When running locally and in unit tests, we are seeing the following warning: `React does not recognize the 'inputRef' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'inputref' instead. If you accidentally passed it from a parent component, remove it from the DOM element.
s`

**To Reproduce**
1. Pass in `inputRef` as a prop to the `<Dropdown />` component
2. See warning logged in `console`

**Expected behavior**
`inputRef` should not be passed into the DOM and no warning should be logged.

**Screenshots**
![Screenshot 2023-05-08 at 3 14 15 PM](https://user-images.githubusercontent.com/9002252/236912205-92ef7766-9e36-4d37-905e-885405b23cba.png)

**Additional context**
From a quick glance through the code, I think this is happening in `useFormLabel`. Some props are collected into `...remainingProps` and returned as part of `fieldProps`, which is then spread into the native `<select />` inside of `Dropdown.tsx`.

**Comment by Josh68** [comment]
+1. Just confirming that we're seeing this issue in MCT after upgrading to MGov DS v8.1.1

**Comment by pwolfert** [comment]
@austindh and @Josh68, what are your apps currently using the `inputRef` for? Focus management?

**Comment by austindh** [comment]
Yes, for focus management.

**Comment by Josh68** [comment]
I'm actually seeing similar warnings on `Autocomplete`, with `focusTrigger` and `labelId`. In this case, these aren't even props we're passing in. The warnings are being generated just because we're using the DS component.

For `inputRef` on the `Dropdown` (at least in one place) we're using it to programmatically keep multiple parts of the UI in sync (can't elaborate more than that without digging in further).

We did not see these errors before the upgrade to DS V8, AFAIK.

**Comment by pwolfert** [comment]
Good information. Thanks, all! We do have an `autoFocus` prop for putting focus on the component, but I realize there might be situations where `inputRef` is easier to use. CC @forrestbaer and @zarahzachz 

The `Autocomplete` warnings I think we've addressed in the current beta version, but overall we can do more to clean up props and make them consistent.

**Comment by pwolfert** [comment]
Fixed in https://github.com/CMSgov/design-system/pull/2566
