### ISSUE TITLE
[Accessibility] h4 in footer component causes heading order issues

### ISSUE THREAD

**Issue by danbivins** [CMSgov/design-system#2565]
**Describe the bug**
Within the footer component is a visually hidden h4 heading <h4>Language resources</h4>. I've seen this consistently cause problems on pages where the h4 doesn't align with the heading structure on the page. 

**To Reproduce**
1. Go to [https://www.healthcare.gov/](https://www.healthcare.gov/) or almost any page on the site
2. Run a WAVE extension report or use ANDI bookmarklet
3. Check out the page structure
4. the page has a missed heading error

I understand what this heading is trying to do but unless we provide a way for teams to determine, for each page, what this heading should be then it doesn't work correctly.

**Comment by pwolfert** [comment]
Tracked under https://jira.cms.gov/browse/WNMGDS-2511

**Comment by zarahzachz** [comment]
Closing. This was resolved in #2926
