### ISSUE TITLE
Allow Alerts to take custom icons

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#2618]
**Description**

Include a high-level description of the issue. 
- What did you expect to happen? That `Alert`s could take custom icons, to use in place of the default icons
- What happened instead? `Alert`s have no OOB way (e.g., prop) to allow them to be rendered with custom icons
- What would you like to see changed? Add a prop that takes an icon to be used in place of the default icon, for any variation

Include any benefits, challenges, or considerations. This can be short and sweet.

MCT designers want to use `Alert` styling, but with icons appropriate to specific use-cases. The default icons seem limiting.

**Steps to reproduce the issue**

1. Step one
2. Step two

**Additional information [optional]**
- Relevant research and support documents
- Screenshots
- Notes
- And so on

**Comment by zarahzachz** [comment]
Closing this issue.

We brought this up with Melissa and at this moment the design system can't allow for Alerts to have custom icons. Feel free to reach out the CMS UX leads if you need to discuss it further. Thanks!
