### ISSUE TITLE
Tabs does not detect TabPanels in React

### ISSUE THREAD

**Issue by lukwallace** [CMSgov/design-system#271]
Attempts to use the example for Tabs results in a seemingly empty div.
### JSX
```
                <Tabs>
                    <TabPanel id="interventions" tab="Interventions">
                        someother stuff here
                    </TabPanel>
                    <TabPanel id="implementation" tab="Implementation Costs">
                        some stuffh ere
                    </TabPanel>
                </Tabs>
```
### html
```
<div>
    <div class="ds-c-tabs" role="tablist"></div>
    <div aria-hidden="true" aria-disabled="false" class="ds-c-tabs__panel" id="interventions" role="tabpanel">someother stuff here</div>
    <div aria-hidden="true" aria-disabled="false" class="ds-c-tabs__panel" id="implementation" role="tabpanel">some stuffh ere</div>
</div>
```

Traced it to the line that detects `TabPanels` (`child.type === TabPanel`); see screenshot

![screen shot 2018-07-16 at 2 57 38 pm](https://user-images.githubusercontent.com/7531099/42786389-e889ac18-890a-11e8-9823-f301b5537a57.png)

Inquiring to change to `child.props && child.props.tab`.

### Environment:
```
"@cmsgov/design-system-core": "^1.23.0",
"react": "16.3.0",
```
Components retrieved via individual exports, i.e.
```
import { TabPanel } from '@cmsgov/design-system-core/dist/components/Tabs/TabPanel';
import { Tabs } from '@cmsgov/design-system-core/dist/components/Tabs/Tabs'; 
```

**Comment by benkutil** [comment]
Hey @lukwallace, thanks for catching this. We may have updated this in 1.25.0. Would you mind updating and seeing if you still find the problem?

If its still a problem, and you have identified a solution, you can submit a pull request and we'll review.
