### ISSUE TITLE
Proper directory setup for using SASS

### ISSUE THREAD

**Issue by barnettj7** [CMSgov/design-system#275]
I am trying to use your framework, and am having trouble getting it initially setup. I would like to use the SASS version and have followed your documentation, with no luck. I am well versed in SASS and should not be an issue once the directory is setup correctly.

Currently I have the following directory setup

Main Directory
- index.html
- node_modules
- fonts
- images
- css

which other files and setup should I include? From there which files do I create or add to import the rest of the Sass and override?

**Comment by benkutil** [comment]
Hi @barnettj7, thanks for your patience in getting a response to you. Do you still need help with getting the Design System Sass files integrated with your project?

**Comment by line47** [comment]
Hey @barnettj7 is this still an issue? If so, please respond or we will be closing this issue.

**Comment by line47** [comment]
Haven't heard back from @barnettj7 so we are closing this issue for now. 
Please re-open if needed.
