### ISSUE TITLE
webfonts, css assets fail to load on sandbox.bluebutton.cms.gov/v1/o/applications/register

### ISSUE THREAD

**Issue by allen-munsch** [CMSgov/design-system#282]
## Description

webfonts, css assets fail to load on sandbox.bluebutton.cms.gov/v1/o/applications/register issues with s3 asset object/bucket key, and deployment URIs for sandbox.bluebutton.cms.gov

**update:**

I'm also seeing this on `https://sandbox.bluebutton.cms.gov/`

S3 related:

 - https://s3.amazonaws.com/content-impl-bbonfhir-com/static/bootstrap/css/less/*
 - https://s3.amazonaws.com/content-impl-bbonfhir-com/static/bootstrap/css/dist/css/bootstrap.css

```
NoSuchKeyThe specified key does not exist.static/bootstrap/css/dist/css/bootstrap.cssCC87AC85E992EC19GgeYLw8li/9KxuL2gClSGzKOffHFZcCJOOY9bUTyy099HRaWz3E6uFfi03Hd7x1qkXMiOVXnUSI=
```

deployment URI related:

 - http://localhost:8000/assets/fonts//*
 - http://localhost:8000/assets/fonts//Bitter-Italic.eot?

Doesn't break functionality, but UX/UI is funky without the CSS.

## Steps to reproduce the issue

Navigation:

1. sign in
2. https://sandbox.bluebutton.cms.gov/v1/o/applications/
3. https://sandbox.bluebutton.cms.gov/v1/o/applications/register/

## Additional information

 - I wasn't sure where to open this issue.

<img width="1438" alt="screen shot 2018-09-28 at 1 11 20 pm" src="https://user-images.githubusercontent.com/33908344/46226045-a89c8580-c320-11e8-80f4-01ceb1bb54d5.png">

Browser Version : Firefox 62.0.2 (64-bit)

list of what looked like related repos, info: 

 - https://github.com/CMSgov/bluebutton-css
 - https://github.com/CMSgov/bluebutton-web-server
 - https://github.com/CMSgov/HealthCare.gov-Styleguide
 - https://github.com/CMSgov/bluebutton-ansible-playbooks-data-sandbox/search?q=sandbox&unscoped_q=sandbox
 - https://github.com/HHSIDEAlab/hhsdevcloud-ansible

**Comment by johnfrenchxyz** [comment]
Hey - @allen-munsch - thanks for raising this issue. I work on the front-end for the Blue Button website and Sandbox. I am going to take a look at this issue and hopefully have a fix for it soon. I probably won't track it in the design system repo here, but you'll definitely see the changes when they go live. I just want you to know that I'll be working on it!

**Comment by allen-munsch** [comment]
@johnfrenchxyz thank you 🎉
