### ISSUE TITLE
Array.includes needs polyfilled for Internet Explorer

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#285]
## Description

`Array.includes` isn't supported in Internet Explorer 11, but was included in the latest release: https://github.com/CMSgov/design-system/commit/752e14fd848c2ab26c2550e5f8e1142e7be3c88e#diff-bc403a3448d8591da046ffb97228eab1R102

## Steps to reproduce the issue

1. Test a masked SSN input field in Internet Explorer 11

## Additional information

![image](https://user-images.githubusercontent.com/371943/47299202-b2e03580-d5e7-11e8-8f60-f9cb7fdaac7a.png)

**Comment by pixelfuture** [comment]
Should the polyfill exist in this project or should we have the consumers of this package be aware that IE11 support requires a polyfill? If responsibility falls on the consumers of this package they can make the decision whether or not to include the polyfill.

**Comment by sawyerh** [comment]
I can't find this documented anywhere unfortunately, but I remember the original intention last year was for the design system to be IE11 compatible. If that's still the case, I think including the polyfill in the relevant module is useful. 

Examples of this in the current codebase:

- https://github.com/CMSgov/design-system/blob/036d0a03ca1c182c71ee997ff8cf088797115b2b/packages/core/src/components/Tabs/Tabs.jsx#L1
- https://github.com/CMSgov/design-system/blob/5675f0b8c1e6bf297bd71a37d539bc0753916d9c/packages/core/src/components/MonthPicker/MonthPicker.jsx#L1

**Comment by pwolfert** [comment]
Thanks for finding this @sawyerh! I've got some time today to turn this into a PR 👍

**Comment by sawyerh** [comment]
I think this got fixed?

**Comment by pwolfert** [comment]
Yep, thanks 👍
