### ISSUE TITLE
Advertise WCAG 2.0 AA compatibility?

### ISSUE THREAD

**Issue by galvarez421** [CMSgov/design-system#287]
## Description

This is not an issue but moreso a question/consideration. It seems that Section 508 is compliant with WCAG 2.0 levels A and AA as of January 18, 2017, per https://www.section508.gov/manage/laws-and-policies and https://www.access-board.gov/attachments/article/1877/ict-final-rule.pdf:

> The Revised 508 Standards and 255 Guidelines incorporate by reference the Web Content Accessibility Guidelines (WCAG) 2.0, a globally-recognized and technologically-neutral set of accessibility guidelines for Web content. For Section 508-covered ICT, all covered Web and non-Web content and software—including, for example, Web sites, intranets, word processing documents, portable document format documents, and project management software—is required, with a few specific exceptions, to conform to WCAG 2.0’s Level A and Level AA Success Criteria and Conformance Requirements

Is the CMS Design System supposed to be compliant with this latest version of Section 508? If so, I think it'd be good to advertise on the website and documentation that the framework is compliant with WCAG 2.0 AA (perhaps, if necessary, with a footnote that said "few specific exceptions" may apply). I think this would help prospective users of the framework realize that this is the case.

**Comment by benkutil** [comment]
Thanks @galvarez421. I'll have @1Copenut follow up on some of the accessibility targets we've had for Design System. Definitely agree that we can do a better job advertising the accessibility capabilities for Design System, and will add that to our roadmap.

**Comment by line47** [comment]
This is related to issue #311

**Comment by line47** [comment]
I think we are addressing this with this page https://design.cms.gov/guidelines/accessibility/
CC @davidakennedy
