### ISSUE TITLE
Badge: Add variation that allows the badge to display block

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#2903]
## What
> Give a brief description of the style, component or pattern you want to propose.

Although you can add `ds-u-display--block` to a `Badge`'s `className`, it will then span the width of its container
Propose to add a `block` variation/prop (or similar) that changes things internally so that the badge will just display on its own line and not stretch.

Options for implementation
- Add `display: block` and `max-width: fit-content` to the `span`s `className`s
- Render with a `div` instead of a `span`

> Please include screenshots, code or guidance.

Badge with `ds-u-display--block` added to `className`, rendered in combination with a `Button`.

<img width="525" alt="image" src="https://github.com/CMSgov/design-system/assets/771447/e14abbe3-abcb-4525-b27f-ba141b17abe7">

## Why
> Explain why you think this should be added to the Design System.
> - Identify the need the item solves.

Badge laying out inline where we want it to layout block

<img width="525" alt="image" src="https://github.com/CMSgov/design-system/assets/771447/67070cab-f476-49f1-a827-0cdfe4fbac9d">

The `Button` can take `ds-u-display--block` and will render correctly, so that's also a workaround in this situation.

> - Have you checked that it doesn't already exist in the Design System?

Yes

> - Can it serve more than one use case and be reusable in multiple scenarios? Please explain.

Yes, just see the examples

> - Please include links to any examples, research or code to support your proposal, if available.

**Comment by pwolfert** [comment]
What about wrapping it in a div in those cases?

**Comment by Josh68** [comment]
> What about wrapping it in a block element like `div` or `p` in those cases?

That was our workaround (actually, now, setting block on the `Button`). And there are combinations of classes that will work, as explained. Just thought this might be a good addition to avoid adding extraneous markup. If it's not worth the work, you may close.

**Comment by pwolfert** [comment]
I don't think it's worth its own special class or logic in the component, and it's partly because the guidelines for when and how to use badges are non-existent. The pattern of using badges needs to be developed more before we start adding more code to them

**Comment by Josh68** [comment]
Fair enough. The only reason I created this was that adding `ds-u-display--block` to the badge screws up its layout. But you're right, the general assumption (not stated outright) is that a badge is meant to lay out inline.
