### ISSUE TITLE
Instructions for site packages and themes should be updated

### ISSUE THREAD

**Issue by jsh-gldbrg** [CMSgov/design-system#291]
## Description

Instructions for site packages and themes should be updated.

Added medicare.gov site package to the design system and followed the [directions for site packages and themes](https://github.com/CMSgov/design-system/wiki/site-packages-and-themes). This yielded no discernible results when running a quick test with a **test-theme**.

## In order to view the **test-theme** successfully in the design system documentation site, the following steps were taken: 

1. Added a 'settings' folder inside **test-theme**'s src folder
2. Within the 'settings' folder, added an`_override.color.scss` file with the following style: `$color-primary: #ff0000;`
3. Included the following cms imports inside the `index.scss` file: 
```
// Design system overrides
@import 'settings/override.color';
// @import 'settings/override.forms';

// Design system core and grid styles
@import '@cmsgov/design-system-core/src/index';
@import '@cmsgov/design-system-layout/src/index';
``` 
4. After running `yarn start:theme`, **test-theme** rendered as expected

**Comment by line47** [comment]
Hey @jsh-gldbrg is this still an issue? If so, would you mind putting in a PR to get this updated?

**Comment by line47** [comment]
Haven't heard back from @jsh-gldbrg so we are closing this issue. 
Please re-open if needed.
