### ISSUE TITLE
Add more font weights for custom fonts

### ISSUE THREAD

**Issue by Josh68** [CMSgov/design-system#2919]
## What
> Give a brief description of the style, component or pattern you want to propose.

On a current initiative, our design team requested that we use Montserrat font with some content in bold and some in "normal" weight. It turns out, MGov only gets 600 weight (aka, bold) Montserrat. For our other font, Rubik, we only get 400 and 600.

Is it possible to at least get 400 Montserrat and possibly 3 weights for each custom font, so designers can choose between them and get the weights they want for specific content?

> Please include screenshots, code or guidance.

## Why
> Explain why you think this should be added to the Design System.
> - Identify the need the item solves.

Lack of custom font font-weight variants

> - Have you checked that it doesn't already exist in the Design System?

Yes

> - Can it serve more than one use case and be reusable in multiple scenarios? Please explain.

Yes (see description)

> - Please include links to any examples, research or code to support your proposal, if available.

**Comment by Josh68** [comment]
Based on discussions in Slack and finding references in [DS guidance](https://design.cms.gov/foundation/typography/body/?theme=medicare#dont), I'm closing this issue. The understanding is that Montserrat is not meant to be used as body text. If there's a desire to change that in the future, we will reach out to have a broader discussion.

**Comment by Josh68** [comment]
Just experimenting with font weights again, and although I could be missing it, I don't see that we have 3 weights for either of our fonts. I went back to the earliest DS docs available and [found this page](https://design.cms.gov/v/3.4.0/utilities/font-weight/), which clearly shows 3 distinct weights. Did we lose an option somehow over time?

**Comment by pwolfert** [comment]
Yeah, it was purposely restricted to simplify designer options.

**Comment by Josh68** [comment]
OK, will close again. If our UX team raises questions about this, we can have that discussion another time.
