### ISSUE TITLE
ChoiceList "hint" states Hints are their own component

### ISSUE THREAD

**Issue by f00dl3** [CMSgov/design-system#2930]
**Description**

Include a high-level description of the issue. 

- What did you expect to happen?    Create a Choice or ChoiceList with choices and set the hint="hint here" inside either the parent element or under the choices node as { hint: "hint" }. Hints should render appropriately per CMS 9 guidelines. "requirementLabel" experiences this same behavior - states Hints are their own component.

- What happened instead?   Received error [Depreciated] Hints are now their own component called 'Hint'

- What would you like to see changed?  Using the CMS.GOV library hint property on Choice or ChoiceList should properly work without depreciation warning.

Include any benefits, challenges, or considerations. This can be short and sweet.

**Steps to reproduce the issue**

1. Step one -- Create <ChoiceList choices={[ label: "Label", value: "value", checked: props.value = "value", hint: ( <React.Fragment> Hint here </React.Fragment> )} type="radio" onChange={handleChange} errorMessage={errorMessage("error here")} name="selectthis" className="ds-u-margin-top--0" />

**Additional information [optional]**
- Relevant research and support documents: code properties inside of @cmsgov/design-system/dist/react-components/types/ChoiceList/ChoiceList.d.ts should be valid.

**Comment by pwolfert** [comment]
@f00dl3, thanks for bringing this to our attention. Turns out that we already have a fix (#2893) for it in our main branch, but we'll plan to pull that into a 9.0.1 patch.

**Comment by pwolfert** [comment]
Fixed in [the 9.0.1 patch](https://github.com/CMSgov/design-system/releases/tag/%40cmsgov%2Fdesign-system%409.0.1)

**Comment by f00dl3** [comment]
Thank you!
