### ISSUE TITLE
Choice List hint wrapping text prematurely

### ISSUE THREAD

**Issue by f00dl3** [CMSgov/design-system#2948]
**Describe the bug**
Text wraps to new line instead of extending to window width. Version 9.0.1.

**To Reproduce**
1. Go to 'https://design.cms.gov/storybook/?path=/story/components-choicelist--default-checkbox'
2. Inspect the document and edit the p element for the choice list hint and set the text to a long text string
4. Text wraps to a new line prematurely. Max width of the element is 460 pixels. Text does not flex into the browser window as it did in v8.x

**Expected behavior**
Text should continue on the same line flexing to the window size as it did in CMS 8.

**Screenshots**

![Screenshot from 2024-02-22 10-01-53](https://github.com/CMSgov/design-system/assets/9626529/789cf7dc-308d-4140-acba-c91f2703348e)

**Comment by zarahzachz** [comment]
This was an intentional change. Closing the issue.
