### ISSUE TITLE
Does this replace the Assets Framework 3.4.1?

### ISSUE THREAD

**Issue by asmith2019** [CMSgov/design-system#302]
Does this replace the Assets Framework 3.4.1? if yes, do you have any replacement for data table sorting and filtering along with JSON support within CMS design system

**Comment by line47** [comment]
Hey @asmith2019 Is this the component you are referring to in the Assets Framework?
https://assets.cms.gov/resources/framework/2.0/Pages/datatables.html

**Comment by line47** [comment]
Hey @asmith2019 is this still an issue? If so, please respond or we will be closing this issue soon.

**Comment by line47** [comment]
Closing due to no response.
