### ISSUE TITLE
Dropdown component can't be accessed via mouse after being set via keyboard

### ISSUE THREAD

**Issue by travisLilleberg** [CMSgov/design-system#3109]
**Overview**
If you set the Dropdown component with the keyboard, and then you click on it with the mouse, it doesn't respond.

**Steps to reproduce the behavior:**
1. Create a basic react app that displays a Dropdown component with a few example options. I'll put some code at the bottom that we're using to test.
2. View the page
3. Tab down to the dropdown
4. Hit spacebar to open it
5. Use the arrow keys to select something
6. Hit spacebar or enter to select your option
7. Now click on the dropdown. In our app, the dropdown doesn't respond to the mouse click.

**Expected behavior**
You should be able to open the Dropdown component with the mouse after selecting something in it with the keyboard.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser [chrome, firefox]
 - Version [10.1.1]
 - Npm version [10.5.0]

**Additional context**
Here's the exact jsx file I used to demonstrate the issue:

```
import { Dropdown } from '@cmsgov/design-system';

const Example = () => {
  return (
    <div>
      <Dropdown
        name={'test'}
        label={'test-dropdown'}
        options={[
          {
            label: 'test thing 1',
            value: 'test value 1',
          },
          {
            label: 'test thing 2',
            value: 'test value 2',
          },
          {
            label: 'test thing 3',
            value: 'test value 3',
          },
        ]}
      />
    </div>
  )
}

export default Example;

```

Thank you.

**Comment by zarahzachz** [comment]
Thanks for reaching out!

I tried recreating the issue, testing in [Storybook](https://design.cms.gov/storybook/?path=/story/components-dropdown--default&globals=theme:core) and locally in a React app example but couldn't recreate the issue. 

Would it be possible for you to swing by our office hours in a couple weeks (6/20) to walk us through what you're seeing? If you can make it, the link to our agenda is [here](https://confluence.cms.gov/display/HCDSG/Design+System+office+hours?flashId=1017669509).

**Comment by travisLilleberg** [comment]
Sorry, I was sick for a little while there. 

I'll pull out some other dependencies in our app and see if maybe they're causing the problem. We're building apps with Vite, which might be different than how you all are building, so I can see if that is causing the discrepancy too.
