### ISSUE TITLE
Consider adding component maturity page

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#311]
## Description

I was looking for information on component maturity states on https://design.cms.gov/ and could not find an explanation. I'd like to recommend creating a page somewhere on the site (maybe under guidelines) that defines the component states.   

In addition, I think it would be nice to update the component states to use plain language 

- Draft (What used to be alpha)
- Work in progress (What used to be beta)
- Ready (Ready to implement)

These components are in either alpha or beta and I'm not sure what that means
https://design.cms.gov/components/dialog/
https://design.cms.gov/components/spinner/
https://design.cms.gov/components/tabs/
https://design.cms.gov/patterns/step-list/
https://design.cms.gov/components/autocomplete/

**Comment by hbillings** [comment]
As an outsider looking to implement the design system, this would be super helpful for me!

**Comment by line47** [comment]
component maturity page has been added https://design.cms.gov/guidelines/component-maturity/
