### ISSUE TITLE
Clarify styling inconsistency in React/non-React versions of vertical nav component

### ISSUE THREAD

**Issue by jenniferthibault** [CMSgov/design-system#313]
## Description

When designing a layout that will use the vertical nav component, I expected each version in the design system site to be consistently styled. Instead I spotted a small variation between them.

It would be helpful for all three of these examples to be consistent — I'm not sure which is the canonical UI style.

## Steps to reproduce the issue

1. Visit the Vertical Nav Component page: https://design.cms.gov/components/vertical-nav/
2. Look at the styles of all three examples on that page

- The nav as used in the site's own navigation uses carets to show sections that expand with sub-sections
  - ![screen shot 2019-02-07 at 2 16 45 pm](https://user-images.githubusercontent.com/11636908/52436945-9d820f00-2ae3-11e9-867c-8c2051b0a964.png)

- The regular HTML component does not use carets to show sections that expand with sub-sections
  - ![screen shot 2019-02-07 at 2 17 12 pm](https://user-images.githubusercontent.com/11636908/52436961-a83ca400-2ae3-11e9-8b51-0200886013f5.png)

- The react component uses carets
  - ![screen shot 2019-02-07 at 2 17 22 pm](https://user-images.githubusercontent.com/11636908/52436975-b094df00-2ae3-11e9-92e9-b88e9bd42656.png)

**Comment by line47** [comment]
Thanks for pointing this out @jenniferthibault **the version with the caret is the proper version**. 
We will use this issue to update design/documentation to reflect that 👍
