### ISSUE TITLE
Add documentation for updating snapshots to PR template

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#317]
## Description

Add information to the pull request template for building snapshots with `yarn update-snapshots`

**Comment by line47** [comment]
@phiden This look accurate to you?

**Comment by phiden** [comment]
@line47 yup, I think so. But it needs to also go into Jira, please 🙌

**Comment by line47** [comment]
https://github.com/CMSgov/design-system/pull/318 adds this
