### ISSUE TITLE
Consider moving wiki pages into a guides folder 

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#320]
## Description
Consider moving the wiki pages into a guides folder to keep documentation in one place as well as have the ability to review, modify, and collaborate on documentation easier. 

Pages can be found here https://github.com/CMSgov/design-system/wiki

**Comment by line47** [comment]
Curious on your thoughts @melwoodard @phiden @1Copenut @pwolfert

**Comment by phiden** [comment]
Is there a marked improvement on the user experience if we make that shift? I can't speak to why the wiki format was chosen to begin with, but it'd be good to make sure that moving away would be a net benefit.

I think we should add this change to the roadmap so that we can prioritize it with the other changes.

**Comment by line47** [comment]
@phiden the benefits are above ☝️the ability to collaborate and PR, review. 
Wiki pages are edit/save only. Not much collaboration. 

We can keep the pages in the wiki but link over to the content in a guides folder.

**Comment by phiden** [comment]
Yeah, sorry I wasn't clear -- I meant are there benefits to the wiki that we'd lose? I think your solution of linking to content is probably a good intermediate step.

**Comment by line47** [comment]
The only thing I can think of we would lose is the right-hand navigation, which I think is fine as we will be linking to the content inline anyways.

**Comment by melwoodard** [comment]
Should this content also get represented on the documentation site? It feels like we have docs in a lot of different places right now.

**Comment by line47** [comment]
I was thinking about separating the documentation in this way.

- Documentation for Design System makers - GitHub repo
- Documentation for Design system users - Design System Website
