### ISSUE TITLE
Checkbox & Radio

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#326]
Use this issue to discuss [this component in the Design System](https://design.cms.gov/components/choice/)

**Comment by jenniferthibault** [comment]
@line47 are these issues meant for external contributors like me to chime in w/ feedback? I

**Comment by line47** [comment]
Yeah they are, this set up is still a work in progress as we are figuring out the best way for folks to work with the Design System. Feel free to drop thoughts here 👍
