### ISSUE TITLE
Fix design for checkbox/radio checked children examples

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#337]
## Description
@bernardwang reported this design issue when using the checked children on small checkboxes.
The expanding line does not line up. 

<img width="360" alt="slack-imgs" src="https://user-images.githubusercontent.com/1449852/53049470-29415700-3465-11e9-8219-45feadad5a03.png">

## To do
- [ ] Update design so small checkbox and radio checked children examples line up properly

**Comment by jenniferthibault** [comment]
Is this checkbox that's followed by a field (pending the user's action) a component somewhere that's part of the design system? @hbillings and I have been looking for this exact interaction pattern! 

Would appreciate if you could point us to it in the design system, or to @bernardwang's use of it if it's in an open source project.

**Comment by bernardwang** [comment]
@jenniferthibault Examples for it were just added! You can find it by searching for `checkedChildren` [here](https://design.cms.gov/components/choice/). 

I believe this functionality was around for a little while, but recently it was worked on to improve a11y, standardize stylings, and some other improvements!

**Comment by jenniferthibault** [comment]
This just made my day!

I'm still relatively new to using the system, so thanks for your patience in pointing it out to me. One thing that might make it easier for other folks to spot in the future might be to display that option in the documentation page as selected by default, so the state with the child field is displayed by default?

Thanks again!

**Comment by bernardwang** [comment]
@jenniferthibault Funny that you say that, `1.31.1` which was just published 45 min ago has that change in the docs, its now selected by default. You ask and you shall receive 😆

**Comment by jenniferthibault** [comment]
:HAPPY-DANCE:!!!
