### ISSUE TITLE
Sketch file responsive behavior improvements

### ISSUE THREAD

**Issue by melwoodard** [CMSgov/design-system#338]
Related to https://github.com/CMSgov/design-system/issues/331

Rework symbol construction in the Design System sketch file to improve responsive behavior - currently resizing some symbols skews their proportions.

**Comment by line47** [comment]
@melwoodard do you know which symbols were having issues?

**Comment by melwoodard** [comment]
@line47 I think this applies to a handful of molecule- or pattern-level components. Off the top of my head, a couple examples of things I've had issues with:

- Help drawer - currently resizing the drawer height stretches everything within it, instead of locking the header and body to the top and the blue footer to the bottom, and not stretching them out
- Text field - if I create a field label that expands to two lines of text, I should be able to resize the height of the component to allow for that extra text, with the input staying the same height and being locked to the bottom of the component.

**Comment by line47** [comment]
This is great context, thank you! 🎉
