### ISSUE TITLE
Sketch file: Provide sample page templates

### ISSUE THREAD

**Issue by melwoodard** [CMSgov/design-system#340]
Related to https://github.com/CMSgov/design-system/issues/331

Explore providing sample page templates - the healthcare.gov UI kit file has templates for a step list page and a form page. Can we bring these in, and are there others we think would be useful? Maybe an app landing page like https://localhelp.healthcare.gov/ ?

**Comment by line47** [comment]
I'm unsure how useful setting up pages would be for the core - I'd be concerned that they would not be used - I might ask in Slack.

**Comment by melwoodard** [comment]
I agree, I think they may be more useful at the child level
