### ISSUE TITLE
Add a one-line start to the package.json scripts section

### ISSUE THREAD

**Issue by 1Copenut** [CMSgov/design-system#342]
## Description
It would be helpful and a bit of a shortcut to add a one-line start command that allows users to install dependencies and start the development server.

The design system is predicated on `Yarn` so any script solutions should use it as the task runner as opposed to `NPM`.

**Comment by line47** [comment]
Couldn't you run `yarn install && yarn start` to accomplish this?

**Comment by line47** [comment]
I think we can close this 
CC @pwolfert and @bernardwang

**Comment by line47** [comment]
We've got a decent set of start up scripts I think this can be closed
