### ISSUE TITLE
Sketch file: Clarify grid layout on desktop

### ISSUE THREAD

**Issue by jenniferthibault** [CMSgov/design-system#344]
Related to a comment originally posted in #331 

## Description

In the `Responsive page templates` page of the Sketch file, the artboards for Desktop and Mobile don't use measurements that conform with [spacing](https://design.cms.gov/layout/spacing/) or [responsive layout](https://design.cms.gov/guidelines/responsive/) guidance on the site.

**Desktop artboard size**
- In the Sketch file, the artboard width for standard desktop is set to 1104px, which seemed non-standard and confusing.
- Based on the breakpoints and variables in the [responsive design](https://design.cms.gov/guidelines/responsive/) page, I would expect it to be set to 1024px, or to provide an annotation about why 1104px was chosen.

Current:
![screen shot 2019-02-19 at 8 39 41 pm](https://user-images.githubusercontent.com/11636908/53059894-8c8fb100-3486-11e9-9020-c8d89b0e293a.png)

**Desktop grid layout**
- In the Sketch file, the grid on the Desktop-sized artboard is set to take up 1040px wide (including outside gutters). In the current settings, the gutter width is set to 29px, which does not conform to the 8-pixel grid defined in the spacing page documentation
- Based on the breakpoints and variables in the [responsive design](https://design.cms.gov/guidelines/responsive/) page, I would expect it to be set to 1024px (or smaller) but definitely not larger. I would also expect that the gutters measure even increments of 8px. Otherwise, I expect to find an annotation telling how these settings are derived. 

Current:
![screen shot 2019-02-19 at 8 06 53 pm](https://user-images.githubusercontent.com/11636908/53059419-bba52300-3484-11e9-9f10-7359a8da01ca.png)

## Additional comments
I haven't gone into the Mobile or Tablet layout yet, but the quirks in the desktop template make me really unsure if I should trust them.

**Comment by jenniferthibault** [comment]
Don't worry I'm not just coming with problems! With a little direction, I think I can help adjust the file to either change the measurements or add notations. 

It would help first to make sure I'm understanding correctly what the grid is made of. Looking at this example from the documentation site: https://design.cms.gov/example/layout.grid.default/
![screen shot 2019-02-20 at 8 03 06 pm](https://user-images.githubusercontent.com/11636908/53135794-98dd4200-354a-11e9-9d05-3f211b786518.png)

If I lined that up to the grid in the sketch file, would it look like this?
![screen shot 2019-02-20 at 8 09 04 pm](https://user-images.githubusercontent.com/11636908/53136024-6da72280-354b-11e9-8764-6200ca0811fe.png)

Where the content body (dark blue) will start on the columns, because the gutter (white) is made of abutting units of padding (light blue, measured by magenta)?
![screen shot 2019-02-20 at 8 07 18 pm](https://user-images.githubusercontent.com/11636908/53136035-73046d00-354b-11e9-825e-0a30fc174284.png)

@hbillings has been reverse engineering this with me, and we're pretty sure that's what's happening, but would be super helpful for someone else to verify that we're not misinterpreting.

**Comment by line47** [comment]
This is fantastic @jenniferthibault and @hbillings trying to find some answers on this 👍
