### ISSUE TITLE
Propose moving a few components to patterns

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#351]
## Description
If we are going to keep the distinction between components and patterns we need to define when something is a component VS pattern.

Proposing to move the following components under patterns as they are more complex and involve multiple components. 

- Date Field
- Help drawer
- Modal dialog
- Month picker
- Tabs
- Vertical navigation

CC @melwoodard @phiden @1Copenut thoughts?

**Comment by melwoodard** [comment]
I think this deserves some discussion on IA. While atomic design is a useful mental model, I also want to keep top of mind where people expect to find a particular item, which won't always match up with that. Though the date field might toe the line between component and pattern on the atomic design scale, from a findability perspective I'd expect to find it in the same area as a text field or dropdown.

**Comment by line47** [comment]
I totally agree and was thinking about where we can find a balance. Maybe everything can be under components and we lose the concept of patterns altogether or rename it to something else.

**Comment by melwoodard** [comment]
Yeah, not unlike USWDS I think a simple approach to groupings might be (1) page templates and (2) anything that's less than that.
