### ISSUE TITLE
Investigate ways to facilitate contribution by outside teams

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#362]
- [ ] Contribute/connect via email
- [x] Contribute/connect via GitHub
- [x] Contribute/connect via Jira (internal only)
- [x] Contribute/connect via Slack (internal only)

**Comment by line47** [comment]
I've created an issue template for proposing a new item to the design system that we can link to from the README or elsewhere in the GitHub docs relating to contribution.

**Comment by line47** [comment]
thoughts here @phiden or @ClassActHarris

**Comment by phiden** [comment]
We may get some insight if anyone responds to the survey, which I'll be pushing to communities for the next few weeks. Otherwise I think your plan is solid.

**Comment by asarazor** [comment]
Our digital services team over at [HHS OIG](https://oig.hhs.gov/) are using the design system. We would be interested in contributing back - at the moment we just have our own internal fork. @phiden would you mind posting that survey here too?

**Comment by line47** [comment]
👋 Hey @asarazor You can find the survey here https://design.cms.gov/

**Comment by line47** [comment]
We need to get an email form set up via screendoor for folks to use to contact the CMS design system team. How do we go about doing that? 

@phiden I think you might know how

**Comment by phiden** [comment]
@line47 can't say that I do. But why does it need to be via screendoor?

**Comment by line47** [comment]
@phiden I thought I remember the issue coming up about making sure the team and steering committee have access to the communication. I'm unsure why it would need to be screendoor. 

Do you have other options in mind?

**Comment by phiden** [comment]
@line47 So that's true, they do need access. But they'd also have to provide (and thus control) the e-mail address and its inbox. Why not a simple form that sends an e-mail?

**Comment by line47** [comment]
I'm all for a simple email form. I've created https://github.com/CMSgov/design-system/issues/399 to capture some details if you want to add @phiden feel free 👍

**Comment by line47** [comment]
Closing this issue
