### ISSUE TITLE
Decide where/how work will be tracked for updates to the Design system

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#363]
- The design system team should look at working in 2-week sprints.
- The design system team should work from a backlog of items, issues, and bugs. 
- The design system team should track work in this GitHub repo for transparency and help facilitate collaboration between design system users, contributors, and maintainers. 
- Investigate how to bridge the gap between GitHub and Jira -https://github.com/apps/jira

**Comment by line47** [comment]
thoughts here @phiden or @ClassActHarris

**Comment by phiden** [comment]
I'm agnostic so long as we're consistent!

**Comment by line47** [comment]
I think we should break out this item into a separate issue 
Investigate how to bridge the gap between GitHub and Jira -https://github.com/apps/jira
