### ISSUE TITLE
Define governance roles (steering committe, design system team)

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#364]
## Review as a team
- https://github.com/CMSgov/design-system/blob/master/GOVERNANCE.md 
- https://github.com/CMSgov/design-system/blob/master/guides/PATTERN-LIFECYCLE.md

## Governance
- [x] Who are the steering committee members?
- [x] Who are the stakeholders and what is there role if any in governance?
- [x] Who are the Design System core team members?
- [x] Do we need Design system rotating team members?
- [x] Who approves changes to the design system?
- [x] Who is responsible for keeping documentation up to date?
- [x] Who actually makes changes to the system’s components, patterns, etc...?
- [x] How are design system changes deployed to live applications?
- [x] How will people find out about changes?

## Pattern lifecycle
- [x] What happens when an existing pattern doesn’t quite work for a specific application? 
Does the pattern get modified? Do you recommend using a different pattern? Does a new pattern need creating?
- [x] How are new pattern requests handled?
- [x] How are old patterns retired?
- [x] What happens when bugs are found?

**Comment by line47** [comment]
@phiden and @ClassActHarris If you all have anything to add please update the issue above 👍

**Comment by phiden** [comment]
lgtm

**Comment by line47** [comment]
Started reviewing this documentation here https://docs.google.com/document/d/15_VCIuiUU1cPSQIIKV0DJotcRMjaZ-11EXGLgYaR8Co/edit?usp=sharing
