### ISSUE TITLE
Audit component functionality

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#373]
Go through components in the design system and verify that the component and pattern functionality is working as expected. 

- Are React `Props` for each component working as expected?
- Are React `Props` documented well?
- Does the component do one thing or several things?
    - If they do more than one then it would be recommended to simplify the component and pair it down.

It seems that many of the HTML components that have JS don’t work. For example, Help drawer and tabs. Should the HTML versions be functional?

**Comment by bernardwang** [comment]
Corresponding Jira ticket was closed, closing this issue too
