### ISSUE TITLE
Audit component consistency

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#379]
Go through components in the design system and verify that the component examples are useful and consistent in how they are worded and used.

- Do the plain HTML and React examples match? Should they?
- Does the example show everything the user would need?
- Should examples be in single code blocks or grouped together? 
    - For example, on the [alerts page](https://design.cms.gov/components/alert/) we break each alert type into it's own example block. Is that helpful or could we combine them all into one example together? 
- All components should have at least an HTML version - this keeps the design system agnostic and allows for folks using other tech stacks or future tech stacks to know what the HTML/CSS/JS looks like.
- If there is not a React example - explain why

**Comment by line47** [comment]
@phiden I'd like to chat about this topic sometime soon so we can have a clearer picture

**Comment by phiden** [comment]
Sounds good. Maybe a good topic for the next coworking session.

**Comment by bernardwang** [comment]
Corresponding Jira ticket was closed, closing this issue too
