### ISSUE TITLE
Add anatomy of a page to the writing documentation page

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#383]
https://github.com/CMSgov/design-system/wiki/Generating-things-101#the-anatomy-of-a-page
Copy this from the wiki over to the writing documentation page at the bottom

**Comment by line47** [comment]
I think this page in the wiki can be deleted - the content found in [writing documentation](https://github.com/CMSgov/design-system/blob/master/guides/WRITING-DOCUMENTATION.md#flags) is much more explanatory and detailed. This appears to be an early draft. 


Thoughts @phiden or @ClassActHarris

**Comment by line47** [comment]
👆 @phiden

**Comment by phiden** [comment]
Go for it

**Comment by line47** [comment]
The old anatomy of a page has been removed
