### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by asarazor** [CMSgov/design-system#385]
Use this issue to discuss [this component in the Design System](https://design.cms.gov/components/select/)

**Comment by asarazor** [comment]
I thought copying the format of the other component specific issues would be appropriate. Here's my actual issue:

Our team at HHS OIG would like to use `<optgroup>` in our React `select` elements. The [ChoiceList](https://design.cms.gov/components/select/#components.select.choicelist) component doesn't support them so we will likely add our own support (we maintain our own fork). Before we do I wanted to ask if you were already working on this or perhaps decided not to for a specific reason?

**Comment by pwolfert** [comment]
@asarazor, if you want it to be rendered as a `select` every time anyway, you can use the [Select](https://design.cms.gov/components/select/#components.select.react) component and create the optgroups yourself like so:

```js
<Select id={id} value={incomeSourceType || ''} name={name} onChange={event => onChange(event.target.value)} onBlur={onBlur}>
  <optgroup label="Example Group 1">
    <option value="a">Option A</option>
    <option value="b">Option B</option>
  </optgroup>
  <optgroup label="Example Group 2">
    <option value="c">Option C</option>
    <option value="d">Option D</option>
  </optgroup>
</Select>
```

We don't have plans that I know of to add optgroup support anytime soon, but it's not out of the question.

**Comment by line47** [comment]
Thanks @pwolfert that sounds right to me in using the `select` component. 
@asarazor If you have something to propose back please create a new issue, we'd love to see what you're working on.

**Comment by bernardwang** [comment]
@asarazor We just added an example to the doc site for `optgroup`, the last one on [this page](https://design.cms.gov/components/dropdown/).
