### ISSUE TITLE
TextField component remove min and max from docs or map them to maxlength and minlength

### ISSUE THREAD

**Issue by dcloud** [CMSgov/design-system#390]
## Description

After reading the [documentation for the `TextField` component](https://design.cms.gov/components/text-field/), I wasn't sure if the `min` or `max` properties corresponded to the `minlength` and `maxlength` properties that limit the number of characters one can enter on an HTML `<textarea>` or `<input type="text">`. I added `max="256"` to a TextField component in a running app, and that did not restrict the input text to 256 characters.

I think `min` and `max` props should either be removed from the TextField component or mapped to the appropriate `minlength` and `maxlength` attributes. `min` and `max` are not valid attributes for HTML `<textarea>` or `<input type="text">` elements.

We _could_ document the ability to use `minlength` and `maxlength` on a TextField component, though that works because the component passes on undocumented props to the html element.

## Steps to reproduce the issue

1. Create a (multiline) TextField and give it a prop of `max="256"`.
2. Enter more than 256 characters. It is allowed. Inspect the underlying HTML element and note that it does not have a `maxlength` attribute.
3. Change prop to `maxlength="256"`
4. Try to enter more than 256 characters and see that character length restriction is enforced by the browser. Also the underlying HTML component has the expected `maxlength` attribute.

**Comment by line47** [comment]
Instead of removing `min` and `max` which are valid for inputs what about if we added `minlength` and `maxlength`. 

My other thought is should we break out `textarea` into it's own component so we don't have this sharing of properties that are not valid for both types of inputs.

**Comment by dcloud** [comment]
`min` and `max` are valid for certain types input elements, yes, but not on all types of inputs. `<input type='text' min="1" />` is invalid, for example. Basically, those attributes are only valid on numeric input types, not text input types (or textareas). `minlength` and `maxlength` are valid on inputs of type 'text', 'search', 'url', 'tel', etc. (in addition to being valid on a textarea)  I'm looking at https://html.spec.whatwg.org/multipage/input.html#input-type-attr-summary for reference.

If we wanted the component to be an abstraction over input types, we could make the React component's `min` and `max` props set the appropriate HTML attribute based on the `type` prop. So `<TextField max="256" />` would render `<input maxlength='256' />` (since 'text' is the default type when none is while `<TextField type='number' max="256" />` would render `<input type='number' max='256' />`. And `<TextField multiline max="256" />` would render `<textarea maxlength='256' />`. This is what I thought might happen when I tried to put a length limit on the TextField component.

If we did not want to create that abstraction, we would want to add `maxLength` and `minLength` component props. Ideally, the component would log a warning if someone used the `max` or `min` prop with any incompatible field `type`. So `<TextField max="256" />` would log a warning message that `max` is not valid on the default text type.

I think I suggested removing `min` and `max` as an option only because there are a number of html input attributes that are not defined as props on the TextField component, and maybe we wouldn't want to get into the business of defining all of those and determining which props were valid for which types of input elements.

**Comment by bernardwang** [comment]
@dcloud 
I agree with you in removing `min` and `max` as options in the docs. All the html input attributes can be passed down to `TextField` if someone wants, but as you said since `TextField` is already an abstraction that gets annoying, and I'm not sure if we want to go down the path of kind of "reimplementing" those native HTML input attributes. 

However, there is discussion of potentially adding a recommended "Reacty" way of handling this sort of validation/user input restrictions with `TextField`. I'd love to hear your thoughts on that!
https://github.com/CMSgov/design-system/issues/514#issuecomment-541890322

**Comment by bernardwang** [comment]
`min` and `max` props have been removed from the `TextField` docs because they are confusing and depend on the element and `type`
