### ISSUE TITLE
Can't toggle between tabs when URL contains an #anchor to the second tab, and the second tab is missing active state

### ISSUE THREAD

**Issue by lizlantz** [CMSgov/design-system#395]
**Describe the bug**
I can't toggle between the usage and guidance tabs when I land on a page via a URL that has the #anchor linking me to the second tab on the page.  

**To Reproduce**
1. Go to https://design.cms.gov/components/form-label/#guidance
2. Try to toggle between the Usage and Guidance tabs

**Expected behavior**
Second tab should have active state (not first), and should be able to toggle between usage and guidance

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Chrome v72.0.3626.121

**Additional context**
Works as expected if I go to the page via https://design.cms.gov/components/form-label/#usage, so thinking it has something to do w/ linking to the second tab?

**Comment by line47** [comment]
Thanks for finding and reporting this @surfbird0713 🎉 
I am able to reproduce this issue 👍
