### ISSUE TITLE
Provide example of validation message in relation to input field

### ISSUE THREAD

**Issue by lizlantz** [CMSgov/design-system#396]
**Description**

Include a high-level description of the issue. 
It'd be helpful to include an example of an input field in your validation message examples here:
https://design.cms.gov/example/components.form-label.react/
https://design.cms.gov/components/form-label/#usage

Include any benefits, challenges, or considerations. This can be short and sweet.
It would eliminate opportunities for misinterpretation and improve consistency.  And hopefully ensure alignment with research/usability test results.

**Comment by line47** [comment]
Hey @surfbird0713, thanks for pointing this out!
Did you see the example here? https://design.cms.gov/components/text-field/
This might be what you are looking for.

Can you say more about the following?
> Include any benefits, challenges, or considerations.

Did you see the Guidance tab under https://design.cms.gov/components/form-label/ ?

**Comment by surfbird0713** [comment]
I didn't see that example on ttps://design.cms.gov/components/text-field/, thanks for pointing that out.

I did see the guidance on https://design.cms.gov/components/form-label/ but was specifically looking for if the DS recommends putting the error message above or below the input.  We're using CMSDS on MACFin and devs placed the error message under the field.  

Not sure what else to say about benefits, challenges or considerations...is there something about my original statement that isn't clear?

**Comment by line47** [comment]
That additional information is great @surfbird0713, thanks for clarifying 👍

**Comment by line47** [comment]
Closing this issue and creating a new issue for validation
