### ISSUE TITLE
Consider adding coding guidelines to component validation checklist

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#401]
There are some coding guidelines that are not captured in the validation checklist that I think should be 

- CSS class naming convention 
- Does the pattern use responsive design if needed
- if React - does it follow the guidelines [here](https://github.com/CMSgov/design-system/blob/master/guides/CODING-GUIDELINES.md#react)

**Comment by forrestbaer** [comment]
Hi Scott, can this be closed? Can I assist in creating a Jira ticket for this issue?
