### ISSUE TITLE
Consider adding a 508 / accessibility statement to our README or wiki

### ISSUE THREAD

**Issue by 1Copenut** [CMSgov/design-system#402]
## What
I'm proposing we codify the steps we take to ensure 508 compliance and functionality in our design system. This could include unpacking details on how we test things like:

* automated testing with aXe
* manual keyboard testing
* screen reader testing
* zoomed layouts
* color (blindness, contrast) testing
* no high-frequency flashing
* parallax, high motion / movement
* dedication to the W3C spec

## Why
The maintainers know we strive for accessible components. Let's show, as well as tell, anyone who's interested in our design system how we work.

**Comment by line47** [comment]
I think some of this is captured in our [component validation checklist](https://github.com/CMSgov/design-system/blob/master/.github/ISSUE_TEMPLATE/component-validation-checklist.md)

**Comment by davidakennedy** [comment]
After some other research related to accessibility and design systems, I ran across this example in the Lightning Design System [around accessibility](https://www.lightningdesignsystem.com/accessibility/overview/). It might be that we could put some of this information in an accessibility section within the Guidelines area.

**Comment by davidakennedy** [comment]
We [added a statement to the site here](https://design.cms.gov/guidelines/accessibility/).

https://github.com/CMSgov/design-system/pull/643
