### ISSUE TITLE
Consider placing markup examples in standalone HTML files

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#408]
**Description**
Currently, the markup for HTML examples is inline which makes is hard to read and reuse.

I'd like to recommend that we move them to standalone files. 
This would make the code easier to read as well as validate and share out.

**Comment by bernardwang** [comment]
@line47 This is in JIRA already split into multiple tickets. Should we maybe just close this ticket?

**Comment by line47** [comment]
Yeah let's close it
