### ISSUE TITLE
Update coding guidelines documentation with testing info (linting, unit, e2e)

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#413]
**Description**
Add a section on testing to the [coding guidelines page](https://github.com/CMSgov/design-system/blob/master/guides/CODING-GUIDELINES.md). 

We’ve got different test suites now (linting, unit, e2e) and I think it’d be good to call those out, what each one does, and what our expectations are for contributions WRT tests.

anything else to add @1Copenut ?

**Comment by forrestbaer** [comment]
I have created a Jira ticket to our backlog to deal with these and more issues with our coding guidelines documentation.
