### ISSUE TITLE
Review design system for WCAG 2.1 color contrast compliance

### ISSUE THREAD

**Issue by 1Copenut** [CMSgov/design-system#423]
**Description**
WCAG 2.1 includes a new color contrast requirement for [adjacent colors to have contrast ratios of 3:1](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#1411-non-text-contrast-aa) or higher. This means a blue button must have a 3:1 or greater contrast to a white or gray background, for example.

We should evaluate our design system for these type of visual patterns, and get ahead of the new standard so that when it's adopted as the baseline to meet, we're well prepared.

**Additional information [optional]**
- [What's New in WCAG 2.1](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21)
- [Understanding WCAG 2.1 - GOV.UK](https://www.gov.uk/service-manual/helping-people-to-use-your-service/understanding-wcag)
- [Contrast Checker](https://contrast-checker.glitch.me/)
- [W3C Optimal Colors to Improve Readability for People with Dyslexia](https://www.w3.org/WAI/RD/2012/text-customization/r11)
- [British Dyslexia Association Style Guide](https://www.bdadyslexia.org.uk/common/ckeditor/filemanager/userfiles/About_Us/policies/Dyslexia_Style_Guide.pdf)

**Comment by davidakennedy** [comment]
After testing these today I didn't find any issues. I used the new-ish focus styles when testing. I'm comfortable with closing this issue and calling it done.

cc: @line47 @bernardwang

**Comment by line47** [comment]
Fantastic, thanks for your work on this @davidakennedy 🎉
