### ISSUE TITLE
Add a text-decoration line-through utility class

### ISSUE THREAD

**Issue by hannaliebl** [CMSgov/design-system#438]
## What
There are a few places in the new card designs for healthcare plans that we use a line-through (on premium values that have been changed by a tax credit, for example.) I was thinking this would be a useful addition to the existing text decoration utilities: https://design.cms.gov/utilities/text-decoration/

**Comment by line47** [comment]
Thanks for this @hannaliebl 👍

**Comment by carynligon** [comment]
https://github.com/CMSgov/design-system/pull/501

**Comment by bernardwang** [comment]
#501 was merged, closing this. Thanks @carynligon!
