### ISSUE TITLE
Add some install steps for getting started with create-react-app

### ISSUE THREAD

**Issue by kingishb** [CMSgov/design-system#464]
## Background
👋 We've used the design system on a few projects created with [create-react-app](https://github.com/facebook/create-react-app). In my past two experiences people spend a day fiddling with the design system trying  to wire in stylesheets and fonts with the create-react-app webpack setup. It'd be great in the docs if there was a recommended way for doing that if you just want the css.

### Possible recommendation
This past time we had no requirements for using sass, and it won't compile with any of the suggested methods. An easy way I worked out today is to directly reference `dist/index.css` in the starter app. A working solution looks like:

```
create-react-app myapp && cd myapp
npm i --save @cmsgov/design-system-core
npm i --save @cmsgov/design-system-layout
```

Then in `src/App.jsx` add the line
```
import "@cmsgov/design-system-core/dist/index.css";
```
If people are okay with this I'd be happy to PR the docs with this!

**Comment by line47** [comment]
Hey @kingishb have you seen this? 
https://github.com/CMSgov/design-system/tree/master/examples/react-app 
If you have ideas for improving the documentation please feel free to submit a PR

**Comment by kingishb** [comment]
@line47 I have seen it! Unfortunately it's not super actionable to use for the `create-react-app` situation. I'll put in a PR.

**Comment by bernardwang** [comment]
@kingishb We've added two new create-react-app examples, one normal and one for typescript!
https://github.com/CMSgov/design-system/tree/master/examples/create-react-app
https://github.com/CMSgov/design-system/tree/master/examples/create-react-app-typescript

**Comment by bernardwang** [comment]
We've also slightly reorganized the documentation on handling font and images, you can take a look [here](https://design.cms.gov/startup/sass-and-css/#setting-asset-paths-to-node_modules)
