### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/design-system#465]
We're currently using the design system on the [eAPD project](/18F/cms-hitech-apd) and I noticed this morning that we're two major versions behind.  Oopsie!  Before I update our dependencies, I wanted to check what has changed to make sure that either:
- there aren't any breaking changes that affect us
- we know what breaking changes to address

So I guess I have two questions!
- is the design system semantically versioned?
- is there a straightforward way to see what has changed/identify potentially breaking changes between major versions?

Benefits include making it easy for consuming projects to know when they can quickly update as part of routine maintenance versus when they need to plan some time to update their own code as part of updating to the latest version of the design system.

**Comment by line47** [comment]
Hey @mgwalker take a look at the Release notes https://github.com/CMSgov/design-system/releases

Is there a location in mind you expected to find this type of information?

**Comment by mgwalker** [comment]
👋 Nope, that's perfect! I almost never think to look at the releases tab, but that's on me. Thanks!
