### ISSUE TITLE
Third-Party Link Disclosure 

### ISSUE THREAD

**Issue by line47** [CMSgov/design-system#499]
Please add your examples of where you have notified users they are leaving a CMS site and going to a third-party site. 

Screenshots and links would be helpful!

**Comment by melwoodard** [comment]
This is not an example, but noting CMS's stated policy on external links: https://www.cms.gov/About-CMS/Agency-Information/Aboutwebsite/PolicyforLinkingtoOutsideWebsites.html

**Comment by melwoodard** [comment]
healthcare.gov link disclosure: https://www.healthcare.gov/privacy/#links

medicare.gov link disclosure: https://www.medicare.gov/privacy-policy#other-sites

**Comment by SparrowSpit** [comment]
On MCT, we are hoping to implement something similar to the above healthcare . gov link that Mel posted.

**Comment by bernardwang** [comment]
The example Melissa gave us was [this alert on blue button](https://www.medicare.gov/index.php/manage-your-health/medicares-blue-button-blue-button-20/blue-button-apps?label=connecttoresearch)

I've heard several ideas thrown around for this, including an interstitial page, external link icons, and a dialog. From what I can tell the dialog was the most commonly agreed upon solution, and it is very similar to the JS alert we have in that example. 

How do people feel about adding a Pattern to the docs that uses the [CMSDS Dialog](https://gyazo.com/d59fedb19607358645b7dc0522fbc989)?

**Comment by melwoodard** [comment]
Are there any strong benefits to using the CMSDS dialog over the JS alert? Thinking particularly about mobile, being able to leverage a native browser modal will likely be a better experience.

**Comment by line47** [comment]
I think the strongest benefit is UI cohesiveness and I feel like the default DOM alert doesn't look great. However, I'm unsure how the mobile experience would be when for example you are on a long page and invoke the CMSDS Modal. I think there is some testing to do here still.

**Comment by melwoodard** [comment]
My concern is that both hc.gov and m.gov seem to be receiving guidance from CMS to use the default DOM alert, so for CMSDS to give alternate guidance is a bit confusing.

**Comment by melwoodard** [comment]
My concern is that both hc.gov and m.gov seem to be receiving guidance from CMS to use the default DOM alert, so for CMSDS to give alternate guidance is a bit confusing. But either way I think if we add documentation around this, we should specify a recommended max character count to ensure it works well on mobile.
