### ISSUE TITLE
Alerts have extra space when not given a heading

### ISSUE THREAD

**Issue by scitech** [CMSgov/design-system#527]
**Describe the bug**

There's a blank space that throws off the alignment in Alerts when there is no heading.

Not sure if this is old or new but noticed it when I updated the design system 2 major versions recently.

**To Reproduce**
1. Create an alert with a body and no heading, and any variant that includes an icon

**Expected behavior**

The first line of the body should be more in alignment with the Icon and there shouldn't be as much blank space at the top of the alert.

**Screenshots**

<img width="723" alt="image" src="https://user-images.githubusercontent.com/4130722/67241627-62c5ca00-f419-11e9-8692-3f0c83d8638f.png">

Viewed on Desktop FF/Chrome.

**Additional context**

N/A

**Comment by bernardwang** [comment]
I believe we actually just fixed this in this PR https://github.com/CMSgov/design-system/pull/513

However I believe we are currently unable to publish the release cuz of CMS npm credential issues :/

**Comment by bernardwang** [comment]
New release was published, so this issue should be resolved
