### ISSUE TITLE
design.cms.gov "Download code and design files" link not working

### ISSUE THREAD

**Issue by tbolt** [CMSgov/design-system#528]
**Describe the bug**
Looks like there was a release for 3.3.0 in package.json but the latest release I can see is 3.2.0.  Since the GitHub link is generated from that package version its trying to serve up the 3.3.0 version that doesn't exist
https://github.com/CMSgov/design-system/blob/master/packages/docs/src/scripts/components/GitHubLinks.jsx

**To Reproduce**
1. Go to https://design.cms.gov
2. Click on `Download code and design files`
3. Look in your local downloads directory
4. Notice an empty `3.3.0` file (at least on macOS)

**Expected behavior**
Expected the same behavior as going to the GitHub releases page and downloading the zip
https://github.com/CMSgov/design-system/releases/tag/v3.2.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 13.0.2

**Comment by line47** [comment]
This should be fixed as we just released 3.3.0, sorry for any confusion 👍
