### ISSUE TITLE
DateField still uses deprecated fieldRef prop

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#544]
**Expected behavior**
When I use the `DateField` component in my production environment, I expect to not receive deprecation warnings in my console about using `fieldRef`

**Screenshots**
![image](https://user-images.githubusercontent.com/371943/68140568-0a52fa00-fefa-11e9-89e7-fa7a8ca749da.png)

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-299
