### ISSUE TITLE
Compiled CSS files no longer included in Release .zip downloads

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#562]
**Describe the bug**
I _think_ this used to work. The [documentation details](https://design.cms.gov/startup/sass-and-css/) that a CSS file is included in a release's Zip download, but it currently is not, and it's not immediately clear how someone could get a minified CSS distribution of the design system.

**To Reproduce**
1. Go to the [latest release](https://github.com/CMSgov/design-system/releases/tag/v3.4.1)
2. Download the "Source code" asset
3. Unzip the download and navigate into `packages/core`

**Expected behavior**
Expect a `packages/core/dist/index.css` file to exist after unzipping the download

**Comment by line47** [comment]
I think this bug was introduced here - updating the gitignore should fix it 👍 Thanks @sawyerh

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-267

**Comment by bernardwang** [comment]
Should be fixed in the latest doc site deployment!
