### ISSUE TITLE
image-style-crop-freeform class now appears to stretch images to width of div

### ISSUE THREAD

**Issue by ClaryPollack** [CMSgov/design-system#564]
**Describe the bug**
When we published our pages, the images wouldn't exceed their file size constraints. Now, in edit, it appears the images stretch to the width of the div.

**Expected behavior**
The images were to fit the width of the div, but only if the width of the div did not exceed the width of the actual image.

**Screenshots**
Here's a screenshot in Edit (even though nothing has changed on our end since Nov 19. The images also have not been edited on our end since before Nov 19.
![image](https://user-images.githubusercontent.com/37819425/70331620-c8c1b180-180d-11ea-9996-65e4c6d1c35d.png)

Here's how the live page appears (how we would like it to appear):

![image](https://user-images.githubusercontent.com/37819425/70331654-de36db80-180d-11ea-8bc6-c9cbb235ae3d.png)

**Desktop (please complete the following information):**
Chrome

**Comment by line47** [comment]
Thanks for reporting this @ClaryPollack 👍 
Can you provide a sample of the HTML code from that screenshot?

**Comment by ClaryPollack** [comment]
Actually, I fixed it by selecting the image in edit, clicking the Embed button, and (on the dropdown) changing the setting from freeform to none. Will do the same for all pages, and appreciate the fast response. The documentation might need to be updated since we were originally instructed to upload images with the expectation that they wouldn't stretch beyond their actual size by default.

There's another issue we just noticed with the ds-u-col class; previously, it would allow columns within a row to display as equal widths but now our pages are forcing everything into one column going straight down in ie. Am going to change the three-column layout on those pages from ds-l-col to ds-l-col--4 and wanted to let you know so you can update the documentation. Thanks again!
