### ISSUE TITLE
Choice component doesn't have a named export, so is difficult to import

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#567]
**Describe the bug**

React components can imported as named imports, for example:

```js
import { Button, TextField } from "@cmsgov/design-system-core";
```

However, the `Choice` component can't be imported this way since it currently lives in the `ChoiceList` subdirectory...I think?

For example, this doesn't work:

```js
import { Choice } from "@cmsgov/design-system-core";
```

**Screenshots**
![image](https://user-images.githubusercontent.com/371943/70630872-4b75b280-1bfa-11ea-81a6-506f64300ed1.png)

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-324

**Comment by bernardwang** [comment]
@sawyerh Do you have more information on how to reproduce this? I'm testing this on 3.4.1 and it seems like `import { Choice } from "@cmsgov/design-system-core"` is working. I believe the component is being exported similar to `Select` [here](https://github.com/CMSgov/design-system/blob/master/packages/core/src/components/index.js#L7)

**Comment by sawyerh** [comment]
I think this is a false alarm on my part. We had a legacy Babel configuration that transformed the imports. Now that we have Webpack treeshaking, we could probably get rid of this:

![image](https://user-images.githubusercontent.com/371943/70805757-b7395600-1d87-11ea-85ed-da040acf381d.png)
