### ISSUE TITLE
IE 11 - Help Drawer - Header Overlap

### ISSUE THREAD

**Issue by erinrep** [CMSgov/design-system#569]
**Describe the bug**
When using a help drawer in Internet Explorer 11, when the title is long and takes up at least 3 lines, the header overlaps with the content.

**To Reproduce**
1. Go to https://design.cms.gov/components/help-drawer/ in IE 11
2. Update the h3 in the example to be very long
3. Note the overlap

**Expected behavior**
The header to not overlap the content

**Screenshots**
![Screen Shot 2019-12-11 at 8 56 31 AM](https://user-images.githubusercontent.com/4550709/70642496-2716d780-1bf4-11ea-86f5-84c3b0d6b719.png)

**chrome for comparison**
![Screen Shot 2019-12-11 at 8 58 18 AM](https://user-images.githubusercontent.com/4550709/70642646-67765580-1bf4-11ea-9fd8-8f436ba9f53a.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser IE11

**Additional context**
position: sticky is not supported in IE 11. This has been ok when using the help drawer with short headers, since the header just scrolls with the content, but the overlap with longer headers is problematic

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-325
