### ISSUE TITLE
Disabled "Primary" <Button> displays incorrect styling

### ISSUE THREAD

**Issue by sawyerh** [CMSgov/design-system#571]
**Describe the bug**

Given the following:

```jsx
<Button disabled variation="primary">
  Submitting...
</Button>
```

I would expect to see the following styling, since this is a "Primary" button:

![image](https://user-images.githubusercontent.com/371943/70658592-492c4c00-1c2c-11ea-91c8-7a7506ea92f2.png)

However, what gets rendered is the "Default" button's disabled styling:

![image](https://user-images.githubusercontent.com/371943/70658652-652fed80-1c2c-11ea-838d-c07b9f3a3cb8.png)

It looks like the "disabled" class is replacing the "primary" class, but it should be included alongside to the "primary" class name.

**Comment by bernardwang** [comment]
Tracked here: 
https://jira.cms.gov/browse/WNMGDS-326

**Comment by bernardwang** [comment]
Should be fixed in the [latest release](https://github.com/CMSgov/design-system/releases/tag/3.4.2)
