### ISSUE TITLE
Dialog Modal Component using deprecated lifecycle method

### ISSUE THREAD

**Issue by SamMade** [CMSgov/design-system#589]
**Describe the bug**
Core is using a version of react-aria-modal which has an open issue to fix using `componentWillMount` method. This is currently deprecated.

Track the progress of that component here: https://github.com/davidtheclark/react-aria-modal/issues/93 to know when to update appropriately.

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-344

**Comment by forrestbaer** [comment]
Most recently tracked in https://jira.cms.gov/browse/WNMGDS-680, please comment for priority as needed there.
