### ISSUE TITLE
Add ability to make borders visible only on certain device widths

### ISSUE THREAD

**Issue by ClaryPollack** [CMSgov/design-system#600]
**Description**

Hello. I'm creating a new page and noticed ds-u-lg-border-right--1 doesn't work. It would be awesome to be able to only show this border on large screens instead of using ds-u-border-right--1. 

The rationale is that the two columns I want to separate with a border on large screens would not need to be separated by a border on smaller screens since the columns will stack on top of each other on smaller screens.

**Comment by bernardwang** [comment]
Thanks for filing this ticket @ClaryPollack! It looks like currently we don't support responsive breakpoints for the border utility classes, but we can work on adding that in for you.

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-352

**Comment by ClaryPollack** [comment]
Thank you so much @bernardwang ! Will follow the Jira ticket. Have a good day :)

**Comment by ClaryPollack** [comment]
Didn't mean to close the issue. Sorry about that!

**Comment by bernardwang** [comment]
@ClaryPollack I looked into this issue and decided it's not common enough of a use case to support via a breakpoint utility class. 

I would recommend directly using the breakpoint values to achieve what you are describing, i.e.:
```

.responsive-col-border {
       border-right: 1rem;
}

@media (min-width: $width-md) {
   .responsive-col-border {
       border-right: 0;
   }
}
```

**Comment by bernardwang** [comment]
@ClaryPollack I looked into this issue and decided it's not common enough of a use case to support via a breakpoint utility class. 

I would recommend directly using the breakpoint values to achieve what you are describing, i.e.:
```

.responsive-col-border {
       border-right: 1rem;
}

@media (min-width: $width-md) {
   .responsive-col-border {
       border-right: 0;
   }
}
```
