### ISSUE TITLE
Remove excess left and right padding on mobile devices

### ISSUE THREAD

**Issue by ClaryPollack** [CMSgov/design-system#601]
Hi and sorry if this issue has already been raised; couldn't find it in the backlog. It might be nice to add a media query for ds-l-col--12.subsite_body to set the padding-left and padding-right to 0 on small devices. Currently, it's set to 16px, which gives a little too much padding on phones.

**Comment by line47** [comment]
Hey @ClaryPollack you can add responsive padding classes and it is documented here https://design.cms.gov/utilities/padding/#utilities.padding.responsive

**Comment by line47** [comment]
Let us know if this is what you were looking for 👍 Thanks!

**Comment by ClaryPollack** [comment]
Hi and thank you for the reply! This doesn't help, unfortunately, as the issue appears to be with the global style sheet. My apologies for citing the 16px left and right padding in the ds-l-col--12.subsite_body element as the problem; that would actually be a healthy amount of padding for mobile devices...

The problem appears to be related to other parent elements. Here's a screenshot so you can see I was careful to remove the left and right padding and margins when I made the pages responsive. You can see quite a bit of left and right padding in areas that can't be controlled without access to the global style sheet:

![image](https://user-images.githubusercontent.com/37819425/72846199-200ccb80-3c6e-11ea-8a84-b5f3405e9851.png)

This screenshot shows where the problem may be in the global style sheets:

![image](https://user-images.githubusercontent.com/37819425/72846275-46cb0200-3c6e-11ea-85b8-8a33c848e359.png)

Thank you for the reply and have a good evening,

Clary

**Comment by line47** [comment]
Thanks for sharing these screenshots 👍 
I see the classes `cms-global-center` and `region-content` in that second screenshot and wanted to let you know that those are not CMSDS classes and must have been created for the website or application you are referring to. 

What is the URL of the application or website you are working on?

**Comment by ClaryPollack** [comment]
Hey and yes, looking at the global code again in dev tools, it does appear to be unrelated to CMSDS. Am curious if this is something OC would fix...or if there could be an override built into CMSDS in the future (i.e., ds-u-margin-left---6 or some type of negative value). I like the CMS Design System and have actually been curious about the possibility of adding a negative margin value, absolute position, etc. in the future. Thanks again for your reply :)

**Comment by ClaryPollack** [comment]
Oops. Meant to provide the URL: https://www.cms.gov/About-CMS/Components/CPI/Medicaid-PI-Strategy

**Comment by bernardwang** [comment]
We don't have much insight into those non CMSDS classes you are dealing with, but I would recommend using a more specific css selector to override that padding. CMSDS doesn't currently have any plans for adding negative margin/padding utilities.
