### ISSUE TITLE
Template for standard design tools

### ISSUE THREAD

**Issue by prabhushan** [CMSgov/design-system#603]
Hi,

I want to design my system using CMS standards. How can i get the templates in a designer like Adobe XD or sketch. 

Please suggest.

**Comment by bernardwang** [comment]
You can download the latest design assets [here](https://github.com/CMSgov/design-system/releases/download/3.5.0/design-system-v3.5.0.zip)

We currently only support Sketch, you can find it under `design-assets`

**Comment by prabhushan** [comment]
Thanks for comment. Fortunately I could use the same in Adobe XD.
