### ISSUE TITLE
Difference between https://assets.cms.gov/ and https://design.cms.gov/

### ISSUE THREAD

**Issue by prabhushan** [CMSgov/design-system#606]
Hi,

I would like to know what is the difference between https://assets.cms.gov/ and https://design.cms.gov/ provided both are coming from CMS.GOV

**Comment by bernardwang** [comment]
Assets.cms.gov is a set of resources that is no longer being supported. It's recommended to use [CMS design system](https://design.cms.gov)

**Comment by prabhushan** [comment]
Thank you.
