### ISSUE TITLE
ds-l-col doesn't work as expected in ie

### ISSUE THREAD

**Issue by ClaryPollack** [CMSgov/design-system#607]
ds-l-col doesn't work as expected in ie; in many cases, it behaves as ds-l-col--1, squishing everything into one column rather than distributing it the remaining width of the row. I've included a screenshot of the same code in ie and Chrome on a page. (Fixed the issue by replacing ds-l-col with ds-l-col--10, but the CMS Design System documentation might need to be updated to instruct people not to use ds-l-col until the bug has been fixed. Thanks!

Chrome (ds-l-col works as expected):
![image](https://user-images.githubusercontent.com/37819425/72844194-05385800-3c6a-11ea-90ec-ec5366440219.png)

ie (ds-l-col behaves as ds-l-col--1 by squishing everything into one column):

![image](https://user-images.githubusercontent.com/37819425/72844258-1ed99f80-3c6a-11ea-806d-9cb7d3c9141c.png)

**Comment by bernardwang** [comment]
@ClaryPollack I'm having some trouble reproducing this issue, could you share the markup for that screenshot? On first glance, it looks like the element being squished should be in a different row element.

**Comment by ClaryPollack** [comment]
Sure. See line 7 (attachment labeled "nested"). ds-l-col works as expected in Chrome but I had to change it to ds-l-col--10 for it to display properly in ie. We've encountered this on all instances that used ds-l-col in ie, and have fixed it in the interim by declaring the exact value of the column. (This is a nested grid, but we've encountered the same issue without nested grids so I've attached a second example, "no-nesting.")
[nested.txt](https://github.com/CMSgov/design-system/files/4099864/nested.txt)
[no-nesting.txt](https://github.com/CMSgov/design-system/files/4099865/no-nesting.txt)

**Comment by bernardwang** [comment]
I tried the code in `no-nesting.txt` in both Chrome and IE11 and I didn't see a difference. I tested this with both the original code in `no-nesting.txt`, and after changing the `ds-l-col--12` class to be just `ds-l-col`. In both they seemed to work normally. 

Do you mind sharing a screenshot of the issue with the code inspector to see which styles are being applied? Also, is it possible that the other columns in that example are not `ds-l-col` as well? `ds-l-col` will only create columns of equal width if the other columns also have `ds-l-col`.

**Comment by bernardwang** [comment]
I tried the code in `no-nesting.txt` in both Chrome and IE11 and I didn't see a difference. I tested this with both the original code in `no-nesting.txt`, and after changing the `ds-l-col--12` class to be just `ds-l-col`. In both they seemed to work normally. 

Do you mind sharing a screenshot of the issue with the code inspector to see which styles are being applied? Also, is it possible that the other columns in that example are not `ds-l-col` as well? `ds-l-col` will only create columns of equal width if the other columns also have `ds-l-col`.
