### ISSUE TITLE
Issues Integrating with Angular 8

### ISSUE THREAD

**Issue by prabhushan** [CMSgov/design-system#608]
Hi,

I have installed using npm install --save @cmsgov/design-system-core for my angular project. But when i include that in the style.css, @import '@cmsgov/design-system-core/src/index'; it could not recognize the file path. But i see the node module under node_modules.

Please help..

**Comment by line47** [comment]
👋 Hey @prabhushan do you have a link to your code or project for us to take a look at?

**Comment by line47** [comment]
Closing this issue. If this is still an issue please reopen.
