### ISSUE TITLE
Help Drawer Heading - needs more flexibility - a11y issue

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#629]
**Describe the bug**
The [Help Drawer](https://design.cms.gov/components/help-drawer/)'s heading is set as an H3 which causes accessibility errors, for a skipped level heading, depending on the page it's used on.

**To Reproduce**
1. Go to [https://www.medicare.gov/plan-compare/#/manage-prescriptions?plan_type=PLAN_TYPE_MAPD&fips=24003&zip=21114&year=2020&lang=en&page=1](https://www.medicare.gov/plan-compare/#/manage-prescriptions?plan_type=PLAN_TYPE_MAPD&fips=24003&zip=21114&year=2020&lang=en&page=1)
2. Click on "Browse drugs A-Z" link
3. The heading in the Help Drawer is coded as an H3
4. Run Wave on the page
5. Wave shows a "skipped heading level" alert

**Expected behavior**
Ideally, we allow for flexibility where the dev can set this heading to be whatever is needed in context to the rest of the page.

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-384

**Comment by line47** [comment]
This PR has been merged here - I think we can close this issue. https://github.com/CMSgov/design-system/pull/638
