### ISSUE TITLE
Yellow background color appears on elements in version 3.6.0

### ISSUE THREAD

**Issue by kleinschmidtj** [CMSgov/design-system#636]
Yellow background color appears on elements in version 3.6.0
<img width="300" alt="Screen Shot 2020-02-26 at 2 59 28 PM" src="https://user-images.githubusercontent.com/57681819/75383111-bd7ca000-58a9-11ea-87ad-a1a207a6fcb1.png">

**To Reproduce**
1. Go to design.cms.gov or open up the local repo for 3.6.0.
2. Click on the side menu.
3. Button is yellow.

**Comment by davidakennedy** [comment]
Hey @kleinschmidtj! Thanks for the report.

This isn't a bug, but a feature. 😅 See the [latest release](https://github.com/CMSgov/design-system/releases/tag/3.6.0). We created new and improved visible focus styles for better accessibility. Previously, the design system relied on browser defaults, which aren't as good from an accessibility perspective.

If you're running a site package, you can change that via the different variables. That way, it fits with whatever visual design needs you have.

**Comment by kleinschmidtj** [comment]
Thanks for the response! I should have read the release notes! 😅
