### ISSUE TITLE
Add errorPosition prop to TextField

### ISSUE THREAD

**Issue by bkerstan** [CMSgov/design-system#663]
The MCT team is in the process of making visual alignment updates to our site package. One change that needs to be made is to have the error message on the `TextField` component appear below the input instead of above. We're suggesting that a prop be added to the `TextField` component, such as `errorPosition`, which can default to `top` but should allow for a `bottom` option.

![image](https://user-images.githubusercontent.com/17154724/77931174-d3e79400-7279-11ea-8344-27a5697d888d.png)

**Comment by bernardwang** [comment]
Commenting here for posterity: 
We have the error above the textfield because it needs to be in the form label for a11y. See: https://adrianroselli.com/2017/01/avoid-messages-under-fields.html"
