### ISSUE TITLE
Remove focusTrigger prop from basic Autocomplete example

### ISSUE THREAD

**Issue by davidakennedy** [CMSgov/design-system#667]
**Describe the bug**
The Autocomplete component has the `focusTrigger` prop that autofocuses on the first field on the page. That can be disruptive to users on page load, unless it's a needed use case like when components are added dynamically, after the application has been rendered.

**To Reproduce**
1. Go to https://design.cms.gov/components/autocomplete/
2. View the autocomplete field, and see that it's automatically focused.

**Expected behavior**
We shouldn't autofocus fields in most cases.

**Comment by bernardwang** [comment]
Thanks for catching and fixing this @davidakennedy!
