### ISSUE TITLE
Sketch UI kit documentation pattern error

### ISSUE THREAD

**Issue by danielladevera-nava** [CMSgov/design-system#678]
**Describe the bug**
(Not sure if this is the right place for this but) In the Sketch UI kit, there's an error in the Vertical nav design. In the Vertical nav component, "Active child section" is typeset in Source Sans Pro when I believe it should be set in Open Sans, as it follows the pattern and that's how it is typeset on the relevant [Design System page](https://design.cms.gov/components/vertical-nav/). 

**To Reproduce**
1. Go to 'CMS Design system Sketch UI Kit'
2. Click on 'Components' page in the left Layers drawer of the side nav
3. Scroll right to 'Component / Vertical nav'

**Expected behavior**
I expected "Active child section" text to be set in Open Sans (not Source Sans Pro).

**Screenshots**
Screenshot of Sketch UI kit:
![image](https://user-images.githubusercontent.com/58006495/79901933-7d2b3100-83c5-11ea-909c-e4555196d44d.png)

Screenshot of Design System web page for the vertical nav component:
![image](https://user-images.githubusercontent.com/58006495/79901723-1ad23080-83c5-11ea-93e0-abd4d9e6ce8b.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version  81.0.4044.113
 - Verified in Sketch UI kit downloaded 04/21/20

**Additional context**
Please let me know if there is a better place to submit this bug or see updates about the Sketch UI kit in general. Thank you for a great resource!

**Comment by line47** [comment]
Thanks for catching this @danielladevera-nava - We've recently started taking a deeper look into our Sketch file and hope to be offering a CMSDS Sketch Library here in the not too distant future. 🚀
