### ISSUE TITLE
HelpDrawerToggle uses inline-block rather than inline when inline prop set to true

### ISSUE THREAD

**Issue by dcloud** [CMSgov/design-system#689]
**Describe the bug**

The `HelpDrawerToggle` DS component has a prop named ‘inline’ that is supposed to set the container span to “display inline or block”, but it adds `display: inline-block`; when `<HelpDrawerToggle inline=true>`. This can cause display issues when the `HelpDrawerToggle` is a string of text in a paragraph element, particularly on small/mobile screen sizes.

**To Reproduce**

Create a `<HelpDrawerToggle inline=true>` with a sentence with of text as the link and place it in a paragraph with other text. See first screenshot.

We are able to override the default style to force `display: inline !important;`, but it seems like `< HelpDrawerToggle inline=true>` should use inline rather than inline-block.

**Expected behavior**

We expect that `<HelpDrawerToggle inline=true>` would apply the `display: inline;` style to the element, not `display: inline-block;`.

**Screenshots**

Using Chrome DevTools at mobile screen sizes

**What we get:**
![localhelp test healthcare gov_(iPhone 5_SE)](https://user-images.githubusercontent.com/279327/80530334-db788680-8966-11ea-9229-a8cbad479b51.png)

**What we expected:**
![localhelp test healthcare gov_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/279327/80530732-72ddd980-8967-11ea-90a7-b5316f685ef4.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 81
Using the responsive design tools in Chrome DevTools to size to screen widths <768px 

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS:  N/A
 - Browser  N/A
 - Version  N/A

**Additional context**

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-457
