### ISSUE TITLE
Help on the design - development handoff

### ISSUE THREAD

**Issue by prabhushan** [CMSgov/design-system#703]
**This is not an issue but seeking recommendations**
Hi,

We are using Sketch with to design the screens based on design system files from design.cms.gov. We noticed that the output of these tools does not have the class names or tags same as design system. 

So should developers manually re-create the HTML tags based on design system from the output of these designer tools? Is there anyways the design tools can retain the class etc.

**Comment by line47** [comment]
Hey @prabhushan can you provide screenshots and more context?

Here is an example of the alert component from Sketch

**Comment by bernardwang** [comment]
@line47 My understanding is the request is for our Sketch file to label symbols with their corresponding CSS classes

**Comment by prabhushan** [comment]
@line47 / @bernardwang  -Sorry for the late response - yes. that is right, we are using Adobe XD where we are able to import the sketch files and also our designer able to design the UI.. but when he exports the the design to HTML - the Adobe XD (sketch, Zeplin also) , generated random HTMLs. So the Developer once again need to re-map the output HTML to the CMS DS documentation.

**Comment by forrestbaer** [comment]
Hello @prabhushan, is this issue still relevant? If so can you update with any current changes to the request if they exist?

**Comment by pwolfert** [comment]
Given how old this issue is and that our Sketch library has changed quite a bit, I'm going to close the issue for now. I think some of these problems could also be alleviated by features of our new documentation site, which is in development.
