### ISSUE TITLE
Irregular Table Headers Currently Unavailable

### ISSUE THREAD

**Issue by ClaryPollack** [CMSgov/design-system#710]
Hey. I need to create a table with an irregular header (like the one found on https://www.w3.org/WAI/tutorials/tables/irregular/). This is just an example but here's a screenshot from the referenced page on w3.org:
![image](https://user-images.githubusercontent.com/37819425/83435215-d006f800-a409-11ea-9a2a-2848be4d7159.png)

Do you know when this functionality will be available with CMS Design System?

Thanks!

**Comment by nichia** [comment]
Hey @ClaryPollack, thank you for raising this. We are in the process of designing a react table component and will explore incorporating this feature.

**Comment by bernardwang** [comment]
@ClaryPollack to clarify, are you mainly requesting an example of a complex table from the CMSDS? Or are you trying to use a Table react component?

**Comment by bernardwang** [comment]
We added a complex table example to the docs site in v2.0.2
https://design.cms.gov/components/table/#components.table.complex
