### ISSUE TITLE
Cannot read property 'checked' of null - Prevents checkedChildren from hiding after triggered

### ISSUE THREAD

**Issue by andrewadcock** [CMSgov/design-system#735]
**Describe the bug**
Using the `<Choice>` component (version 3.7.2) with option checkedChildren does not disappear when unchecked. A console error `Cannot read property 'checked' of null` shows.

**To Reproduce**
1. Add demo code snippet for `Radio buttons with children`
2. Click on 'Radio A' (children of Radio B should hide)
3. Check console for error `Cannot read property 'checked' of null`

**Expected behavior**
When radio is unchecked, checkedChildren should hide.

**Screenshots**
https://drive.google.com/file/d/15t2M6DvWFi0F8lXdTN1D3KYtS-C0F4aI/view?usp=sharing

**Desktop:**
 - OS: Windows, Ubuntu
 - Browser Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by nichia** [comment]
Hi @andrewadcock. Thank you for the screen capture. Can you also share the code snippet and url (if available) for this screen.

**Comment by nichia** [comment]
@andrewadcock - Release 3.7.2 contains the fix for this issue. Can you help confirm the application is using this version?

**Comment by andrewadcock** [comment]
It appears that my issue stemmed from a docker-container problem. This issue can be closed. Thank you!
