### ISSUE TITLE
More advanced header options (similar to USDWS)

### ISSUE THREAD

**Issue by danielladevera-nava** [CMSgov/design-system#742]
## What
For websites with more complicated IA and content, an extended header and/or megamenu capabilities for the header (similar to the offerings in the USWDS).

## Why
- On cloud.cms.gov, we have a complicated IA that currently relies on the side nav / documentation pattern to support setting expectations with users about what to expect in a section and support users navigating through that content.
- Have you checked that it doesn't already exist in the Design System?
  - Yes.
- Can it serve more than one use case and be reusable in multiple scenarios? Please explain.
  - I believe other sites using the CMS DS would potentially benefit from a more advanced header component. 
- Please include links to any examples, research or code to support your proposal, if available.
  - [USWDS's extended header component](https://designsystem.digital.gov/components/header/#extended)
> When to use the extended header with megamenu component
> - Lots of sections. Use an extended header with mega menu if you have too many sections in your horizontal navigation to fit comfortably in the basic header format.
> - Secondary links or specific calls to action. It’s also useful if you’d like to include secondary links or specific calls to action in addition to the main content navigation — for example Log in and Sign up links — or if you’d like to include more than six links in any of your dropdowns.
> - Deep hierarchy. If you’d like to include more than six links in any of your dropdowns.
  - Note: all the above apply to cloud.cms.gov

### Images
Current side nav situation on the documentation page of cloud.cms.gov, as an example.
![image](https://user-images.githubusercontent.com/58006495/87490803-6fb7c880-c5fb-11ea-965f-aedfa73da3a0.png)

Extended header w/megamenu component from USWDS
![image](https://user-images.githubusercontent.com/58006495/87490967-d0470580-c5fb-11ea-8bb1-ae1a2959ac32.png)

**Comment by pwolfert** [comment]
Right now our primary users/brands have very different headers. This may be an opportunity to unify the designs of multiple brands, but I don't see that happening anytime soon. I'm going to close this for now. If it could be general enough of a component to be usable on CMS.gov, Healthcare.gov, and Medicare.gov, we would reconsider. CC @line47
