### ISSUE TITLE
Links to source code on documentation appear broken

### ISSUE THREAD

**Issue by kleinschmidtj** [CMSgov/design-system#754]
**Describe the bug**
I clicked "View source file" here and it appears to be a broken link. Not sure if there are more instances of these old links!

**To Reproduce**
1. Go to [https://design.cms.gov/components/vertical-nav/](https://design.cms.gov/components/vertical-nav/)
2. Click on "View source file" below `<VerticalNav>`
3. See error

**Screenshots**
![Screen Shot 2020-07-27 at 9 17 59 AM](https://user-images.githubusercontent.com/57681819/88546234-12078100-cfea-11ea-99ca-59871a7f30db.png)

**Comment by line47** [comment]
Hey @kleinschmidtj - thanks for letting us know about this broken link! 

We're in the process of updating the documentation site so some things have moved around.

You can find the VerticalNav component code here 
https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/VerticalNav/VerticalNavItem.jsx

And other component code here: 
https://github.com/CMSgov/design-system/tree/master/packages/design-system/src/components

**Comment by kleinschmidtj** [comment]
Thanks!

**Comment by line47** [comment]
This has been fixed with the latest release 🎉 

when you click view source file on https://design.cms.gov/components/vertical-nav/ you are taken to https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/VerticalNav/VerticalNav.jsx
