### ISSUE TITLE
_link.scss imported twice

### ISSUE THREAD

**Issue by pwolfert** [CMSgov/design-system#780]
**Describe the bug**
`_link.scss` is imported twice—once by `packages/design-system/src/styles/components/_Alert.scss` and once by `packages/design-system/src/styles/base/index.scss`. It looks like the rules are correctly deduplicated in the distributed CSS files, but when I'm using the SCSS and webpack dev server I get duplicated rules in my stylesheet. I do not believe this affects our production applications. It's just a minor annoyance during debugging.

I found this while trying to debug #779

**Expected behavior**
I expect the file to be imported only once.

**Comment by line47** [comment]
Hey @pwolfert this issue has been fixed as part of this work but has yet to be released https://github.com/CMSgov/design-system/pull/774
