### ISSUE TITLE
TypeScript definition for StepList steps doesn't support substeps

### ISSUE THREAD

**Issue by pwolfert** [CMSgov/design-system#845]
We're trying to add steps with a `steps` property. It's supported in the UI but not the type definition.

**Comment by bernardwang** [comment]
@line47 I wonder if this would be a good opportunity to go ahead and move the `StepList` component into the HCgov DS. We could potentially define updated `StepList` definition files in the HCgov DS right now without rereleasing the core. We'd still have to ensure its safe to start deprecating `StepList` in the core CMSDS and get a formal sign off from our POs.

**Comment by pwolfert** [comment]
I was thinking the same thing—that it's just another reason to move it.

**Comment by line47** [comment]
@kathleenmeditz and I are in the middle of some Step List exploration work so hopefully after that we can have a clearer picture if deprecating at the core design system level makes sense. 👍

**Comment by bernardwang** [comment]
Work tracked here: https://jira.cms.gov/browse/WNMGDS-657

**Comment by bernardwang** [comment]
> @kathleenmeditz and I are in the middle of some Step List exploration work so hopefully after that we can have a clearer picture if deprecating at the core design system level makes sense. 👍

As I understand, that StepList exploration is mostly around enhancing it or exploring other progress related components right? Can that be separate from the question of where we include a StepList component?

**Comment by line47** [comment]
The only thing I'm not sure clear on yet if teams from Medicare Design System are using the Step List

**Comment by bernardwang** [comment]
I'm pretty sure MCT isnt, and I think other Mgov teams shouldnt be too hard to confirm. However I am wondering if there are other non HC.gov teams that are using it. We should also thoroughly plan out a deprecation/communication process, but both of these things I'm thinking can be separate from the design work.

**Comment by bernardwang** [comment]
A fix will be included in the next HCgov DS release after this PR is reviewed and merged. It will also be fixed in the next core release after [this PR](https://github.com/CMSgov/design-system/pulls) is merged and released.

**Comment by bernardwang** [comment]
Fixed in [v2.2.1](https://github.com/CMSgov/design-system/releases/tag/core-2.2.1)
