### ISSUE TITLE
Help Drawer trigger needs role=button

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#859]
**Describe the bug**
Currently the trigger that opens the Help Drawer component is coded as a link rather than a button. This seems incorrect for the purpose of the trigger. 

Whereas a link's purpose is to direct the user to a new page a button's purpose is to toggle an interface, open a modal, play a video, etc. This can be confusing for a screenreader user as they will hear a link read to them rather than a button and are selected by enter key or space bar respectively. 

**To Reproduce**
1. Go to https://design.cms.gov/example/components.help-drawer.react-help-drawer/
2. tab to "toggle the help drawer" link
3. attempt to open help drawer with your space bar (also, use VoiceOver to hear "link" vs. "button")
4. nothing happens

**Expected behavior/Solution**
A user should not have friction when they come to the trigger and wonder what will really happen. We can solve this by adding either `role=button` to the trigger link or simply change it to a `<button>` element.

**Desktop**
 - OS: Mac OS
 - Browser: Safari
 - Version e.g. 14.0

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-676

**Comment by bernardwang** [comment]
In the latest 2.2.0 release we updated the <HelpDrawerToggle> to be a button. This change will also be included in the next HCgov DS release after [this PR](https://github.com/CMSgov/hcgov-design-system/pull/8) is reviewed and merged
