### ISSUE TITLE
Autocomplete component not working in my system

### ISSUE THREAD

**Issue by thetif** [CMSgov/design-system#877]
**Describe the bug**
I am trying to use the Autocomplete component in my application, but it is not rendering correctly. My repo is https://github.com/CMSgov/eAPD. I tried replacing the whole app with something just rendering the Autocomplete component. Initially it worked, but then when I tried to incorporate it into the app again it didn't and I couldn't get it to work on it's own again.

**Expected behavior**
It should behave like the example on the guide, but instead it is unresponsive.

**Screenshots**
I took screen shots of the rendered component from the guide and the rendered version in my code.

<img width="629" alt="Screen Shot 2020-11-09 at 4 00 39 PM" src="https://user-images.githubusercontent.com/62778/99091385-cf1fe800-259d-11eb-9be1-b428b911685b.png">

![Screen Shot 2020-11-09 at 3 59 08 PM](https://user-images.githubusercontent.com/62778/99091421-dba44080-259d-11eb-8aae-06f0348c1539.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome and firefox

**Additional context**
We are using node version 10, react version 16.13.1, and design-system version 2.1.1.

**Comment by nichia** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-700
