### ISSUE TITLE
Add to the radio and checkbox inputs to meet WCAG 2.1 target size standards

### ISSUE THREAD

**Issue by SparrowSpit** [CMSgov/design-system#879]
**Description**

 
- Currently the checkbox and radio input components have a touch target of 32px (height) (see attached screenshot)
- Per the WCAG 2.1 standards, we should provide a touch target size of 44x44px. This will benefit our mouse (and other pointer type) users as well as those on mobile who may struggle with fine motor control. 

Check out the documentation here 
https://www.w3.org/WAI/WCAG21/Understanding/target-size.html 

![checkbox](https://user-images.githubusercontent.com/10236001/99305683-19190000-2822-11eb-8569-0eaad098bae4.png)

**Comment by line47** [comment]
Tracked in Jira here - https://jira.cms.gov/browse/WNMGDS-702

**Comment by line47** [comment]
There are a few ways I'm thinking we could tackle this 

- Increase the padding around the radio/checkbox to meet the 44px min height 
- Increase the checkbox itself to meet the 44px min height 
- Some combination of making the checkbox larger and adding padding around the radio/checkbox

**Comment by zarahzachz** [comment]
@SparrowSpit I'm curious about this. Does this only apply to the checkbox/radio itself, or can the touch affordance include the adjacent label, which is also interactive?

**Comment by SparrowSpit** [comment]
Closing this as we are fine for AA standards and the standard I listed above is AAA.
