### ISSUE TITLE
for child design systems meta <title> should be amended and utag should be removed

### ISSUE THREAD

**Issue by whatbird** [CMSgov/design-system#891]
**Describe the bug**

there are still some "CMS" bits leftover if you create a child design system, notably these two things:

* the `<title>` tag should use the `options.name` instead of the hard-coded "CMS" string, see: https://github.com/CMSgov/design-system/blob/3cff4bbc327ead90ec6d6ed5b5a9cebab08c31b1/packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js#L78-L92
* i expect that you probably do not want [the cmsgov utag reference](https://github.com/CMSgov/design-system/blob/3cff4bbc327ead90ec6d6ed5b5a9cebab08c31b1/packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js#L69) shipping on all child systems. perhaps the inclusion of `analytics` should be conditional on just the parent DS.

**To Reproduce**

1. create a new child design system according to the documentation
2. update values (esp: name) in `cmsds.config.js`
3. `yarn start` to build docs pages
4. see "CMS" specific content in docs, as above

**Comment by bernardwang** [comment]
Tracked here: https://jira.cms.gov/browse/WNMGDS-711

**Comment by bernardwang** [comment]
Fixed in [v2.2.1](https://github.com/CMSgov/design-system/releases/tag/core-2.2.1)
