### ISSUE TITLE
Add React 17 to Peer dependency 

### ISSUE THREAD

**Issue by pixelfuture** [CMSgov/design-system#954]
**Description**
Add React 17 as a peer dependency. There should be no breaking changes according the [React blog](https://reactjs.org/blog/2020/10/20/react-v17.html).

When attempting to update the CMS Design system version we get an error message locally since we are running React 17.

Error message received when running `npm update`:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from @cmsgov/design-system-core@3.7.2
```

**Steps to reproduce the issue**

1. Install React 17 or later
2. Install or update @cmsgov/design-system-core

**Comment by bernardwang** [comment]
It looks like this is the old design system packages, which have been deprecated in favor of `@cmsgov/design-system`. Migrating to the updated version and package would fix this issue.
You can find [info on how to upgrade on the doc site](https://design.cms.gov/startup/migrating-v2/), as well as a detailed [changelist on our github](https://github.com/CMSgov/design-system/releases).

**Comment by sawyerh** [comment]
@bernardwang I think this issue is still present with the newest `@cmsgov/design-system` package, but maybe only when running the NPM version 7+. I see this on a fresh install. Looks like it may be from `focus-trap-react`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^17.0.2" from @next/react-dev-overlay@11.0.1
npm ERR!   node_modules/@next/react-dev-overlay
npm ERR!     @next/react-dev-overlay@"11.0.1" from next@11.0.1
npm ERR!     node_modules/next
npm ERR!       next@"^11.0.1" from the root project
npm ERR!   6 more (next, react-dom, styled-jsx, use-subscription, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"0.14.x || ^15.0.0 || ^16.0.0" from focus-trap-react@6.0.0
npm ERR! node_modules/@cmsgov/design-system/node_modules/focus-trap-react
npm ERR!   focus-trap-react@"^6.0.0" from @cmsgov/design-system@2.7.1
npm ERR!   node_modules/@cmsgov/design-system
npm ERR!     @cmsgov/design-system@"^2.7.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
